- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
    - !type:AgeRequirement
      age: 6 # WL-Changes-AgeRequirement
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  # WL-Skills-start
  bonusSkillPoints: 17
  defaultSkills:
    Chemistry: 3
    Medicine: 2
  # WL-Skills-end

- type: startingGear
  id: ChemistGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetMedical

- type: chameleonOutfit
  id: ChemistChameleonOutfit
  job: Chemist
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesGlassesChemical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabChem
    gloves: ClothingHandsGlovesLatex
