using System.Linq;
using Content.Shared._WL.Barks; // WL-Changes
using Content.Shared.Corvax.TTS;
using Content.Client.UserInterface.Controls;
using Content.Shared.Corvax.CCCVars;
using Content.Shared.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls; // WL-Changes
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.VoiceMask;

[GenerateTypedNameReferences]
public sealed partial class VoiceMaskNameChangeWindow : FancyWindow
{
    public Action<string>? OnNameChange;
    public Action<string?>? OnVerbChange;
    public Action? OnToggle;
    public Action? OnAccentToggle;
    public Action<string>? OnVoiceChange; // Corvax-TTS
    // WL-Changes-Start: Speech barks
    public Action<string>? OnBarkChange;
    public Action<float>? OnBarkPitchChange;

    private List<(string, string)> _verbs = new();
    private List<TTSVoicePrototype> _voices = new(); // Corvax-TTS
    private List<BarkPrototype> _barks = new();

    private string? _verb;
    private float _barkPitch = SpeechBarksComponent.DefaultPitch;
    // WL-Changes-End
    public VoiceMaskNameChangeWindow()
    {
        RobustXamlLoader.Load(this);
        NameSelectorSet.OnPressed += _ =>
        {
            OnNameChange?.Invoke(NameSelector.Text);
        };

        SpeechVerbSelector.OnItemSelected += args =>
        {
            OnVerbChange?.Invoke((string?) args.Button.GetItemMetadata(args.Id));
            SpeechVerbSelector.SelectId(args.Id);
        };

        ToggleButton.OnPressed += args => OnToggle?.Invoke();
        ToggleAccentButton.OnPressed += args => OnAccentToggle?.Invoke();

        // Corvax-TTS-Start
        if (IoCManager.Resolve<IConfigurationManager>().GetCVar(CCCVars.TTSEnabled))
        {
            TTSContainer.Visible = true;
            ReloadVoices(IoCManager.Resolve<IPrototypeManager>());
        }
        // Corvax-TTS-End

        // WL-Changes-Start: Speech barks
        ReloadBarks(IoCManager.Resolve<IPrototypeManager>());
        BarkPitchSelector.OnTextEntered += OnBarkPitchCommitted;
        BarkPitchSelector.OnFocusExit += OnBarkPitchCommitted;
        // WL-Changes-End
    }

    public void ReloadVerbs(IPrototypeManager proto)
    {
        foreach (var verb in proto.EnumeratePrototypes<SpeechVerbPrototype>())
        {
            _verbs.Add((Loc.GetString(verb.Name), verb.ID));
        }
        _verbs.Sort((a, b) => a.Item1.CompareTo(b.Item1));
    }

    public void AddVerbs()
    {
        SpeechVerbSelector.Clear();

        AddVerb(Loc.GetString("chat-speech-verb-name-none"), null);
        foreach (var (name, id) in _verbs)
        {
            AddVerb(name, id);
        }
    }

    private void AddVerb(string name, string? verb)
    {
        var id = SpeechVerbSelector.ItemCount;
        SpeechVerbSelector.AddItem(name);
        if (verb is {} metadata)
            SpeechVerbSelector.SetItemMetadata(id, metadata);

        if (verb == _verb)
            SpeechVerbSelector.SelectId(id);
    }

    // Corvax-TTS-Start
    private void ReloadVoices(IPrototypeManager proto)
    {
        VoiceSelector.OnItemSelected += args =>
        {
            VoiceSelector.SelectId(args.Id);
            if (VoiceSelector.SelectedMetadata != null)
                OnVoiceChange!((string)VoiceSelector.SelectedMetadata);
        };
        _voices = proto
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.RoundStart)
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();
        for (var i = 0; i < _voices.Count; i++)
        {
            var name = Loc.GetString(_voices[i].Name);
            VoiceSelector.AddItem(name);
            VoiceSelector.SetItemMetadata(i, _voices[i].ID);
        }
    }
    // Corvax-TTS-End

    // WL-Changes-Start: Speech barks
    private void ReloadBarks(IPrototypeManager proto)
    {
        BarkSelector.OnItemSelected += args =>
        {
            BarkSelector.SelectId(args.Id);
            if (BarkSelector.SelectedMetadata is string bark)
                OnBarkChange?.Invoke(bark);
        };

        _barks = proto
            .EnumeratePrototypes<BarkPrototype>()
            .Where(o => o.RoundStart)
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();

        for (var i = 0; i < _barks.Count; i++)
        {
            BarkSelector.AddItem(Loc.GetString(_barks[i].Name));
            BarkSelector.SetItemMetadata(i, _barks[i].ID);
        }
    }

    private void OnBarkPitchCommitted(LineEdit.LineEditEventArgs args)
    {
        if (!float.TryParse(args.Text, out var pitch) || !float.IsFinite(pitch))
        {
            BarkPitchSelector.Text = _barkPitch.ToString("F2");
            return;
        }

        pitch = SpeechBarksComponent.SanitizePitch(pitch);
        BarkPitchSelector.Text = pitch.ToString("F2");
        if (pitch == _barkPitch)
            return;

        _barkPitch = pitch;
        OnBarkPitchChange?.Invoke(pitch);
    }

    public void UpdateState(
        string name,
        string? verb,
        bool active,
        bool accentHide,
        LocId titleText,
        string voice,
        string barkVoice,
        float barkPitch)
    {
        NameSelector.Text = name;
        _verb = verb;
        ToggleButton.Pressed = active;
        ToggleAccentButton.Pressed = accentHide;
        Title = Loc.GetString(titleText);
        for (int id = 0; id < SpeechVerbSelector.ItemCount; id++)
        {
            if (string.Equals(verb, SpeechVerbSelector.GetItemMetadata(id)))
            {
                SpeechVerbSelector.SelectId(id);
                break;
            }
        }

        // Corvax-TTS-Start
        var voiceIdx = _voices.FindIndex(v => v.ID == voice);
        if (voiceIdx != -1)
            VoiceSelector.Select(voiceIdx);
        // Corvax-TTS-End

        var barkIdx = _barks.FindIndex(v => v.ID == barkVoice);
        if (barkIdx != -1)
            BarkSelector.Select(barkIdx);
        _barkPitch = SpeechBarksComponent.SanitizePitch(barkPitch);
        BarkPitchSelector.Text = _barkPitch.ToString("F2");
    }
    // WL-Changes-End
}
