using System.Linq;

using Content.Shared._WL.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WL.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    private enum NanoChatViewMode
    {
        Chats,
        Lookup,
    }

    /// <summary>Starts a new chat with a directory contact (number, name, job).</summary>
    public event Action<uint, string, string?>? NewChat;
    public event Action<uint>? SelectChat;
    public event Action<uint>? DeleteChat;
    public event Action<uint, string>? SendMessage;
    public event Action? ToggleMute;
    public event Action? ToggleListNumber;

    private NanoChatUiState? _state;
    private NanoChatViewMode _viewMode;
    private uint? _selectedChat;
    private uint? _pendingNewChat;
    private uint? _deleteConfirmationChat;
    private bool _scrollToBottom;
    private uint? _lastRenderedChat;
    private const string DirectoryVisibleTexture = "/Textures/_WL/Interface/NanoChat/eye-open.svg.192dpi.png";
    private const string DirectoryHiddenTexture = "/Textures/_WL/Interface/NanoChat/eye-slash.svg.192dpi.png";
    private const float MessageBubbleMaxWidth = 300f;

    private static readonly Color AccentColor = Color.FromHex("#58BCE8");
    private static readonly Color SelectedEntryColor = Color.FromHex("#27404D");
    private static readonly Color DimTextColor = Color.FromHex("#88939E");
    private static readonly StyleBoxFlat HeaderPanel = CreatePanelStyle("#1E2328", AccentColor);
    private static readonly StyleBoxFlat IncomingMessagePanel = CreatePanelStyle("#1D2126", Color.FromHex("#2B333C"));
    private static readonly StyleBoxFlat OutgoingMessagePanel = CreatePanelStyle("#1E252B", Color.FromHex("#1E252B"));
    private static readonly Color MessageTextColor = Color.FromHex("#D5DCE4");

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        HorizontalExpand = true;
        VerticalExpand = true;

        LookupButton.OnPressed += _ =>
        {
            _viewMode = _viewMode == NanoChatViewMode.Chats
                ? NanoChatViewMode.Lookup
                : NanoChatViewMode.Chats;
            Rebuild();
        };
        WelcomeLookupButton.OnPressed += _ =>
        {
            _viewMode = NanoChatViewMode.Lookup;
            Rebuild();
        };
        MuteButton.OnPressed += _ => ToggleMute?.Invoke();
        ListNumberButton.OnPressed += _ => ToggleListNumber?.Invoke();
        DeleteChatButton.OnPressed += _ =>
        {
            if ((_selectedChat ?? _state?.CurrentChat) is not { } number)
                return;

            if (_deleteConfirmationChat != number)
            {
                _deleteConfirmationChat = number;
                DeleteChatButton.ToolTip = Loc.GetString("nanochat-delete-chat-confirm");
                DeleteChatButton.ModulateSelfOverride = Color.FromHex("#C95C5C");
                return;
            }

            ResetDeleteConfirmation();
            _selectedChat = null;
            DeleteChat?.Invoke(number);
            Rebuild();
        };
        SendButton.OnPressed += _ => SubmitMessage();
        MessageInput.OnTextEntered += _ => SubmitMessage();
        MessageInput.OnTextChanged += args => UpdateComposerState(args.Text);

        NumberInput.OnTextChanged += args => UpdateStartChatState(args.Text);
        NumberInput.OnTextEntered += _ => SubmitStartChat();
        StartChatButton.OnPressed += _ => SubmitStartChat();
    }

    public void UpdateState(NanoChatUiState state)
    {
        var shouldFollowBottom = ShouldFollowBottom(state);
        var selectedChat = _selectedChat;
        var selectionConfirmed = selectedChat != null && selectedChat == state.CurrentChat;
        var keepRenderedConversation = selectionConfirmed &&
                                       _state is { } previous &&
                                       CanKeepRenderedConversation(previous, state, selectedChat.GetValueOrDefault());

        if (selectionConfirmed ||
            _selectedChat is { } unavailable && !state.Recipients.ContainsKey(unavailable))
            _selectedChat = null;

        if (_pendingNewChat is { } pending)
        {
            if (state.CurrentChat == pending && state.Recipients.ContainsKey(pending))
            {
                _viewMode = NanoChatViewMode.Chats;
                NumberInput.Clear();
            }

            _pendingNewChat = null;
        }

        _state = state;

        if (shouldFollowBottom)
            RequestScrollToBottom();

        Rebuild(!keepRenderedConversation);
    }

    private void Rebuild(bool rebuildConversation = true)
    {
        if (_state is null)
            return;

        TitleLabel.Text = Loc.GetString("nanochat-title");
        TitleLabel.FontColorOverride = AccentColor;
        OwnNumberLabel.Text = Loc.GetString("nanochat-own-number", ("number", _state.OwnNumber.ToString("D4")));
        BellIcon.Visible = !_state.NotificationsMuted;
        BellMutedIcon.Visible = _state.NotificationsMuted;
        MuteButton.ToolTip = Loc.GetString(_state.NotificationsMuted
            ? "nanochat-enable-notifications"
            : "nanochat-disable-notifications");
        LookupButton.Text = Loc.GetString(_viewMode == NanoChatViewMode.Lookup
            ? "nanochat-return"
            : "nanochat-search");
        LookupButton.ToolTip = Loc.GetString(_viewMode == NanoChatViewMode.Lookup
            ? "nanochat-return-to-chats"
            : "nanochat-search-contacts");
        ListNumberButton.Pressed = _state.ListNumber;
        ListNumberIcon.TexturePath = _state.ListNumber
            ? DirectoryVisibleTexture
            : DirectoryHiddenTexture;
        ListNumberButton.ToolTip = Loc.GetString(_state.ListNumber
            ? "nanochat-hide-from-search"
            : "nanochat-show-in-search");

        var lookingUp = _viewMode == NanoChatViewMode.Lookup;
        ChatView.Visible = !lookingUp;
        LookupView.Visible = lookingUp;

        if (lookingUp)
        {
            RebuildLookup();
            return;
        }

        RebuildChatList();
        if (rebuildConversation)
            RebuildMessages();
    }

    private void RebuildLookup()
    {
        LookupList.RemoveAllChildren();
        UpdateStartChatState(NumberInput.Text);

        var directory = _state?.Directory;
        if (directory is null || directory.Count == 0)
        {
            LookupList.AddChild(CreateDirectoryEmptyLabel());
            return;
        }

        var anyEntries = false;

        foreach (var recipient in directory)
        {
            if (_state!.OwnNumber == recipient.Number)
                continue;

            anyEntries = true;

            var button = new Button
            {
                HorizontalExpand = true,
                ToolTip = recipient.JobTitle is { } job
                    ? $"{recipient.Name} ({job})  #{recipient.Number:D4}"
                    : $"{recipient.Name}  #{recipient.Number:D4}",
            };

            var labels = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(4, 2),
            };
            labels.AddChild(new Label
            {
                Text = FormatListText(recipient.Name),
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = recipient.Name,
            });
            labels.AddChild(new Label
            {
                Text = FormatLookupText(recipient),
                StyleClasses = { "LabelSubText" },
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = button.ToolTip,
            });
            button.AddChild(labels);

            button.OnPressed += _ =>
            {
                RequestNewChat(recipient);
            };
            LookupList.AddChild(button);
        }

        if (!anyEntries)
            LookupList.AddChild(CreateDirectoryEmptyLabel());
    }

    private void RebuildChatList()
    {
        ChatList.RemoveAllChildren();

        var contacts = _state!.Recipients.Values.OrderBy(recipient => recipient.Name).ToList();

        NoChatsLabel.Text = Loc.GetString("nanochat-no-chats");
        NoChatsLabel.Visible = contacts.Count == 0;

        if (contacts.Count == 0)
        {
            ChatList.AddChild(NoChatsLabel);
            return;
        }

        foreach (var recipient in contacts)
        {
            var isSelected = (_selectedChat ?? _state.CurrentChat) == recipient.Number;
            var preview = GetLastMessagePreview(recipient.Number);
            var button = new Button
            {
                HorizontalExpand = true,
                Pressed = isSelected,
                ToggleMode = true,
                ToolTip = recipient.Name,
                ModulateSelfOverride = isSelected ? SelectedEntryColor : null,
            };
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(3, 2),
            };
            var labels = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            labels.AddChild(new Label
            {
                Text = FormatListText(recipient.Name),
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = recipient.Name,
            });
            labels.AddChild(new Label
            {
                Text = FormatListText(preview),
                StyleClasses = { "LabelSubText" },
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = preview,
            });
            row.AddChild(labels);
            if (recipient.HasUnread && !isSelected)
            {
                row.AddChild(new PanelContainer
                {
                    MinSize = new Vector2i(6, 6),
                    MaxSize = new Vector2i(6, 6),
                    VerticalAlignment = VAlignment.Center,
                    Margin = new Thickness(4, 0, 0, 0),
                    PanelOverride = new StyleBoxFlat { BackgroundColor = AccentColor },
                });
            }
            button.AddChild(row);
            button.OnPressed += _ =>
            {
                _selectedChat = recipient.Number;
                SelectChat?.Invoke(recipient.Number);
                Rebuild();
            };
            ChatList.AddChild(button);
        }
    }

    private void RebuildMessages()
    {
        var state = _state;
        if (state is null)
            return;

        MessageList.RemoveAllChildren();

        var activeChat = _selectedChat ?? state.CurrentChat;
        if (_deleteConfirmationChat != activeChat)
            ResetDeleteConfirmation();

        var hasChats = state.Recipients.Count > 0;
        var focusComposer = activeChat is not null && !MessageInputContainer.Visible;
        WelcomeView.Visible = !hasChats;
        NoConversationSelectedView.Visible = hasChats && activeChat is null;
        ConversationView.Visible = activeChat is not null;
        MessageInputContainer.Visible = activeChat is not null;

        if (focusComposer)
            MessageInput.GrabKeyboardFocus();

        WelcomeTitle.Text = Loc.GetString("nanochat-welcome-title");
        WelcomeTitle.FontColorOverride = AccentColor;
        WelcomeDetails.Text = Loc.GetString("nanochat-welcome-details");
        WelcomeLookupButton.Text = Loc.GetString("nanochat-search-contacts");
        NoConversationSelectedLabel.Text = Loc.GetString("nanochat-select-chat");
        NoConversationSelectedLabel.FontColorOverride = AccentColor;
        NoConversationSelectedDetails.Text = Loc.GetString("nanochat-select-chat-details");

        if (activeChat is not { } current)
            return;

        var hasRecipient = state.Recipients.TryGetValue(current, out var selectedRecipient);
        CurrentChatDetails.Text = hasRecipient && selectedRecipient.JobTitle is { } jobTitle
            ? $"{jobTitle} · #{current:D4}"
            : $"#{current:D4}";
        CurrentChatDetails.ToolTip = hasRecipient
            ? selectedRecipient.Name
            : Loc.GetString("nanochat-unknown-contact");
        CurrentChatHeader.PanelOverride = HeaderPanel;
        CurrentChatHeader.ModulateSelfOverride = null;
        if (_deleteConfirmationChat == null)
            DeleteChatButton.ToolTip = Loc.GetString("nanochat-delete-chat");
        UpdateComposerState(MessageInput.Text);

        if (_lastRenderedChat != current)
            RequestScrollToBottom();

        if (!state.Messages.TryGetValue(current, out var messages) || messages.Count == 0)
        {
            MessageList.AddChild(new Label
            {
                Text = Loc.GetString("nanochat-no-messages"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(4),
                StyleClasses = { "LabelSubText" },
            });
            RequestScrollToBottom();
            return;
        }

        foreach (var message in messages)
        {
            var own = message.Sender == state.OwnNumber;
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };
            if (own)
                row.AddChild(new BoxContainer { HorizontalExpand = true });
            var card = new PanelContainer
            {
                MinWidth = 84,
                MaxWidth = MessageBubbleMaxWidth,
                Margin = new Thickness(1),
                PanelOverride = own ? OutgoingMessagePanel : IncomingMessagePanel,
                ModulateSelfOverride = own ? Color.FromHex("#C2D9E6") : Color.FromHex("#B8C0C9"),
                StyleClasses = { "AngleRect" },
            };
            var contents = new BoxContainer { Orientation = LayoutOrientation.Vertical, Margin = new Thickness(8, 6, 8, 5) };
            var messageLabel = new RichTextLabel
            {
                MaxWidth = MessageBubbleMaxWidth - 22f,
                HorizontalExpand = true,
            };
            messageLabel.SetMessage(FormattedMessage.FromUnformatted(message.Content), MessageTextColor);
            contents.AddChild(messageLabel);
            contents.AddChild(new Label
            {
                Text = message.DeliveryFailed
                    ? Loc.GetString("nanochat-message-status-failed", ("time", message.Timestamp.ToString(@"hh\:mm")))
                    : message.Timestamp.ToString(@"hh\:mm"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Right,
                FontColorOverride = DimTextColor,
                Margin = new Thickness(0, 3, 0, 0),
            });
            card.AddChild(contents);
            row.AddChild(card);
            if (!own)
                row.AddChild(new BoxContainer { HorizontalExpand = true });
            MessageList.AddChild(row);
        }

        _lastRenderedChat = current;
        RequestScrollToBottom();
    }

    private void SubmitMessage()
    {
        if (_state is null)
            return;

        var number = _selectedChat ?? _state.CurrentChat;
        var text = MessageInput.Text.Trim();

        if (number is not { } recipient || string.IsNullOrWhiteSpace(text) || text.Length > NanoChatMessage.MaxLength)
            return;

        SendMessage?.Invoke(recipient, text);
        MessageInput.Clear();
        UpdateComposerState(string.Empty);
        RequestScrollToBottom();
    }

    private void UpdateComposerState(string text)
    {
        var length = text.Length;
        var hasChat = _state?.CurrentChat != null || _selectedChat != null;
        var tooLong = length > NanoChatMessage.MaxLength;

        SendButton.Disabled = !hasChat || string.IsNullOrWhiteSpace(text) || tooLong;
        SendButton.ModulateSelfOverride = SendButton.Disabled
            ? Color.FromHex("#59616B")
            : Color.FromHex("#3F5C6C");
        CharacterCount.Visible = tooLong;
        if (tooLong)
            CharacterCount.Text = Loc.GetString("nanochat-message-too-long", ("current", length), ("max", NanoChatMessage.MaxLength));
    }

    private void SubmitStartChat()
    {
        if (!uint.TryParse(NumberInput.Text.Trim(), out var number) || number == _state?.OwnNumber)
            return;

        NanoChatRecipient? directoryEntry = null;
        if (_state?.Directory is { } directory)
        {
            foreach (var candidate in directory)
            {
                if (candidate.Number != number)
                    continue;

                directoryEntry = candidate;
                break;
            }
        }

        if (directoryEntry is { } knownContact)
        {
            RequestNewChat(knownContact);
            return;
        }

        _pendingNewChat = number;
        NewChat?.Invoke(number, Loc.GetString("nanochat-unknown-contact"), null);
        UpdateStartChatState(NumberInput.Text);
    }

    private void UpdateStartChatState(string text)
    {
        StartChatButton.Disabled = _pendingNewChat != null ||
                                   !uint.TryParse(text.Trim(), out var number) ||
                                   number == _state?.OwnNumber;
    }

    private void RequestNewChat(NanoChatRecipient recipient)
    {
        if (_pendingNewChat != null)
            return;

        _pendingNewChat = recipient.Number;
        NewChat?.Invoke(recipient.Number, recipient.Name, recipient.JobTitle);
        UpdateStartChatState(NumberInput.Text);
    }

    private string GetLastMessagePreview(uint number)
    {
        if (_state!.Messages.TryGetValue(number, out var messages) && messages.Count > 0)
        {
            var message = messages[^1];
            return message.Sender == _state!.OwnNumber
                ? Loc.GetString("nanochat-message-preview-own", ("message", message.Content))
                : message.Content;
        }

        return Loc.GetString("nanochat-no-messages");
    }

    private static string FormatListText(string text)
    {
        const int maxCharacters = 28;
        return text.Length <= maxCharacters ? text : text[..(maxCharacters - 1)] + "…";
    }

    private static string FormatLookupText(NanoChatRecipient recipient)
    {
        var details = recipient.JobTitle is { Length: > 0 }
            ? $"{recipient.JobTitle} · #{recipient.Number:D4}"
            : $"#{recipient.Number:D4}";

        const int maxCharacters = 30;
        return details.Length <= maxCharacters ? details : details[..(maxCharacters - 1)] + "…";
    }

    private static Label CreateDirectoryEmptyLabel()
    {
        return new Label
        {
            Text = Loc.GetString("nanochat-directory-empty"),
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(4, 6),
            StyleClasses = { "LabelSubText" },
        };
    }

    private void ResetDeleteConfirmation()
    {
        _deleteConfirmationChat = null;
        DeleteChatButton.ToolTip = Loc.GetString("nanochat-delete-chat");
        DeleteChatButton.ModulateSelfOverride = null;
    }

    private static StyleBoxFlat CreatePanelStyle(string background, Color border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = border,
            BorderThickness = new Thickness(1),
        };
    }

    private void RequestScrollToBottom()
    {
        _scrollToBottom = true;
    }

    private bool ShouldFollowBottom(NanoChatUiState nextState)
    {
        var previousState = _state;
        var previousChat = _selectedChat ?? previousState?.CurrentChat;
        var nextChat = _selectedChat ?? nextState.CurrentChat;

        if (nextChat == null)
            return previousChat != null;

        if (previousChat != nextChat)
            return true;

        if (previousState == null)
            return true;

        var previousCount = previousState.Messages.TryGetValue(nextChat.Value, out var previousMessages)
            ? previousMessages.Count
            : 0;
        var nextCount = nextState.Messages.TryGetValue(nextChat.Value, out var nextMessages)
            ? nextMessages.Count
            : 0;

        if (nextCount <= previousCount)
            return false;

        var latestMessage = nextMessages![^1];
        return latestMessage.Sender == nextState.OwnNumber || IsNearBottom();
    }

    private bool IsNearBottom()
    {
        if (!MessagesScroll.Visible)
            return true;

        var hiddenHeight = MessageList.DesiredSize.Y - (MessagesScroll.VScroll + MessagesScroll.Size.Y);
        return hiddenHeight <= 28f || MathHelper.CloseToPercent(hiddenHeight, 0f, 0.08f);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_scrollToBottom || !MessagesScroll.Visible)
            return;

        _scrollToBottom = false;
        MessagesScroll.VScrollTarget = float.PositiveInfinity;
    }

    private static bool CanKeepRenderedConversation(NanoChatUiState previous, NanoChatUiState next, uint chat)
    {
        if (!previous.Recipients.TryGetValue(chat, out var previousRecipient) ||
            !next.Recipients.TryGetValue(chat, out var nextRecipient) ||
            previousRecipient.Name != nextRecipient.Name ||
            previousRecipient.JobTitle != nextRecipient.JobTitle)
            return false;

        var previousMessages = previous.Messages.GetValueOrDefault(chat);
        var nextMessages = next.Messages.GetValueOrDefault(chat);
        if (previousMessages == null || nextMessages == null)
            return previousMessages == nextMessages;

        return previousMessages.SequenceEqual(nextMessages);
    }
}
