using System.Linq;

using Content.Client.RichText;
using Content.Shared._WL.CartridgeLoader.Cartridges;
using Content.Shared._WL.NanoChat;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WL.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    private enum NanoChatViewMode
    {
        Chats,
        Lookup,
        Settings,
    }

    /// <summary>Starts a new chat with a directory contact.</summary>
    public event Action<uint>? NewChat;
    public event Action<uint>? DeleteChat;
    public event Action<NanoChatConversationId>? SelectConversation;
    public event Action<NanoChatConversationId, string>? SendMessage;
    public event Action<string, List<uint>>? CreateGroup;
    public event Action<NanoChatConversationId, string>? RenameGroup;
    public event Action<NanoChatConversationId, uint>? AddGroupMember;
    public event Action<NanoChatConversationId, uint>? RemoveGroupMember;
    public event Action<NanoChatConversationId, uint, bool>? SetGroupAdmin;
    public event Action<NanoChatConversationId>? LeaveGroup;
    public event Action<NanoChatConversationId>? DeleteGroup;
    public event Action<NanoChatConversationId>? ToggleGroupMute;
    public event Action<uint, bool>? SetBlocked;
    public event Action<NanoChatConversationId>? LoadOlderMessages;
    public event Action? ToggleMute;
    public event Action? ToggleListNumber;

    private NanoChatUiState? _state;
    private NanoChatViewMode _viewMode;
    [Dependency] private IEntitySystemManager _entitySystem = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private SpriteSystem _spriteSystem = default!;

    private NanoChatConversationId? _selectedConversation;
    private uint? _pendingNewChat;
    private NanoChatConversationId? _deleteConfirmation;
    private bool _scrollToBottom;
    private NanoChatConversationId? _lastRenderedConversation;
    private bool _loadingOlder;
    private float _historyHeightBeforeLoad;
    private readonly HashSet<uint> _selectedGroupMembers = new();
    private NanoChatConversationId? _addingMembersToGroup;
    private uint? _groupNameDraftFor;
    private bool _restoreScrollAfterPrepend;
    private const string DirectoryVisibleTexture = "/Textures/_WL/Interface/NanoChat/eye-open.svg.192dpi.png";
    private const string DirectoryHiddenTexture = "/Textures/_WL/Interface/NanoChat/eye-slash.svg.192dpi.png";
    private const string GroupTexture = "/Textures/_WL/Interface/NanoChat/group.png";
    private const string CrownTexture = "/Textures/_WL/Interface/NanoChat/crown.png";
    private const float MessageBubbleMaxWidth = 300f;
    internal const float FollowBottomThreshold = 28f;

    private static readonly Color AccentColor = Color.FromHex("#58BCE8");
    private static readonly Color SelectedEntryColor = Color.FromHex("#27404D");
    private static readonly Color DimTextColor = Color.FromHex("#88939E");
    private static readonly StyleBoxFlat HeaderPanel = CreatePanelStyle("#1E2328", AccentColor);
    private static readonly StyleBoxFlat IncomingMessagePanel = CreatePanelStyle("#1D2126", Color.FromHex("#2B333C"));
    private static readonly StyleBoxFlat OutgoingMessagePanel = CreatePanelStyle("#1E252B", Color.FromHex("#1E252B"));
    private static readonly Color MessageTextColor = Color.FromHex("#D5DCE4");

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();
        HorizontalExpand = true;
        VerticalExpand = true;

        LookupButton.OnPressed += _ =>
        {
            _viewMode = _viewMode == NanoChatViewMode.Chats
                ? NanoChatViewMode.Lookup
                : NanoChatViewMode.Chats;
            Rebuild();
        };
        WelcomeLookupButton.OnPressed += _ =>
        {
            _viewMode = NanoChatViewMode.Lookup;
            Rebuild();
        };
        MuteButton.OnPressed += _ => ToggleMute?.Invoke();
        ListNumberButton.OnPressed += _ => ToggleListNumber?.Invoke();
        DeleteChatButton.OnPressed += _ =>
        {
            if (GetActiveConversation() is not { Type: NanoChatConversationType.Direct } conversation)
                return;

            if (_deleteConfirmation != conversation)
            {
                _deleteConfirmation = conversation;
                DeleteChatButton.ToolTip = Loc.GetString("nanochat-delete-chat-confirm");
                DeleteChatButton.ModulateSelfOverride = Color.FromHex("#C95C5C");
                return;
            }

            ResetDeleteConfirmation();
            _selectedConversation = null;
            DeleteChat?.Invoke(conversation.Id);
            Rebuild();
        };
        SendButton.OnPressed += _ => SubmitMessage();
        MessageInput.OnTextEntered += _ => SubmitMessage();
        MessageInput.OnTextChanged += args => UpdateComposerState(args.Text);

        NumberInput.OnTextChanged += args => UpdateStartChatState(args.Text);
        NumberInput.OnTextEntered += _ => SubmitStartChat();
        StartChatButton.OnPressed += _ => SubmitStartChat();
        DirectorySearchInput.OnTextChanged += _ => RebuildLookup();
        CreateGroupButton.OnPressed += _ => SetGroupComposerVisible(!GroupComposer.Visible);
        CancelCreateGroupButton.OnPressed += _ => SetGroupComposerVisible(false);
        NewGroupNameInput.OnTextChanged += _ => UpdateGroupComposer();
        ConfirmCreateGroupButton.OnPressed += _ => SubmitCreateGroup();
        ConversationSettingsButton.OnPressed += _ =>
        {
            _groupNameDraftFor = null;
            _viewMode = NanoChatViewMode.Settings;
            Rebuild();
        };
        SettingsBackButton.OnPressed += _ =>
        {
            _groupNameDraftFor = null;
            _viewMode = NanoChatViewMode.Chats;
            Rebuild();
        };
        RenameGroupButton.OnPressed += _ => SubmitRenameGroup();
        MuteConversationButton.OnPressed += _ => ToggleCurrentConversationMute();
        LeaveOrBlockButton.OnPressed += _ => LeaveOrBlockCurrentConversation();
        DeleteGroupButton.OnPressed += _ => DeleteCurrentGroup();
        MessagesScroll.OnScrolled += TryLoadOlderMessages;
    }

    public void UpdateState(NanoChatUiState state)
    {
        var shouldFollowBottom = ShouldFollowBottom(state);
        var selectedConversation = _selectedConversation;
        var stateConversation = GetStateConversation(state);
        var selectionConfirmed = selectedConversation != null && selectedConversation == stateConversation;
        var keepRenderedConversation = selectionConfirmed &&
                                       _state is { } previous &&
                                       CanKeepRenderedConversation(previous, state, selectedConversation.GetValueOrDefault());

        if (selectionConfirmed ||
            _selectedConversation is { } unavailable && !HasConversation(state, unavailable))
            _selectedConversation = null;

        if (_pendingNewChat is { } pending)
        {
            if (state.CurrentChat == pending && state.Recipients.ContainsKey(pending))
            {
                _viewMode = NanoChatViewMode.Chats;
                NumberInput.Clear();
            }

            _pendingNewChat = null;
        }

        _state = state;

        if (_loadingOlder)
        {
            _loadingOlder = false;
            Rebuild();
            _restoreScrollAfterPrepend = true;
            return;
        }

        if (shouldFollowBottom)
            RequestScrollToBottom();

        Rebuild(!keepRenderedConversation);
    }

    private void Rebuild(bool rebuildConversation = true)
    {
        if (_state is null)
            return;

        TitleLabel.Text = Loc.GetString("nanochat-title");
        TitleLabel.FontColorOverride = AccentColor;
        OwnNumberLabel.Text = Loc.GetString("nanochat-own-number", ("number", _state.OwnNumber.ToString("D4")));
        BellIcon.Visible = !_state.NotificationsMuted;
        BellMutedIcon.Visible = _state.NotificationsMuted;
        MuteButton.ToolTip = Loc.GetString(_state.NotificationsMuted
            ? "nanochat-enable-notifications"
            : "nanochat-disable-notifications");
        LookupButton.Text = Loc.GetString(_viewMode == NanoChatViewMode.Lookup
            ? "nanochat-return"
            : "nanochat-search");
        LookupButton.ToolTip = Loc.GetString(_viewMode == NanoChatViewMode.Lookup
            ? "nanochat-return-to-chats"
            : "nanochat-search-contacts");
        ListNumberButton.Pressed = _state.ListNumber;
        ListNumberIcon.TexturePath = _state.ListNumber
            ? DirectoryVisibleTexture
            : DirectoryHiddenTexture;
        ListNumberButton.ToolTip = Loc.GetString(_state.ListNumber
            ? "nanochat-hide-from-search"
            : "nanochat-show-in-search");
        CreateGroupButton.Text = Loc.GetString("nanochat-group-new");
        DirectorySearchInput.PlaceHolder = Loc.GetString("nanochat-directory-search-placeholder");

        var lookingUp = _viewMode == NanoChatViewMode.Lookup;
        var hasChats = _state.Recipients.Count > 0 || _state.Groups.Count > 0;
        ChatView.Visible = !lookingUp && hasChats;
        WelcomeView.Visible = !lookingUp && !hasChats;
        LookupView.Visible = lookingUp;

        if (lookingUp)
        {
            RebuildLookup();
            return;
        }

        RebuildChatList();
        if (rebuildConversation)
            RebuildMessages();

        if (_viewMode == NanoChatViewMode.Settings)
            RebuildConversationSettings();
    }

    private void RebuildLookup()
    {
        LookupList.RemoveAllChildren();
        UpdateStartChatState(NumberInput.Text);
        CreateGroupButton.Visible = _addingMembersToGroup == null;

        var directory = _state?.Directory;
        if (directory is null || directory.Count == 0)
        {
            LookupList.AddChild(CreateDirectoryEmptyLabel());
            return;
        }

        var anyEntries = false;
        var query = DirectorySearchInput.Text.Trim();

        foreach (var recipient in directory)
        {
            if (_state!.OwnNumber == recipient.Number ||
                (_addingMembersToGroup is { } addingTo &&
                 _state.Groups.TryGetValue(addingTo.Id, out var targetGroup) &&
                 targetGroup.Members.ContainsKey(recipient.Number)) ||
                (query.Length > 0 &&
                 !recipient.Name.Contains(query, StringComparison.CurrentCultureIgnoreCase) &&
                 !(recipient.JobTitle?.Contains(query, StringComparison.CurrentCultureIgnoreCase) ?? false)))
                continue;

            anyEntries = true;

            var button = new Button
            {
                HorizontalExpand = true,
                ToolTip = recipient.JobTitle is { } job
                    ? $"{recipient.Name} ({job})  #{recipient.Number:D4}"
                    : $"{recipient.Name}  #{recipient.Number:D4}",
                Pressed = GroupComposer.Visible && _selectedGroupMembers.Contains(recipient.Number),
                ToggleMode = GroupComposer.Visible,
            };
            if (GroupComposer.Visible &&
                _selectedGroupMembers.Count >= NanoChatGroup.MaxMembers - 1 &&
                !_selectedGroupMembers.Contains(recipient.Number))
                button.Disabled = true;

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(4, 2),
                SeparationOverride = 4,
            };
            row.AddChild(CreateJobIcon(recipient.JobIcon));

            var labels = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            labels.AddChild(new Label
            {
                Text = FormatListText(recipient.Name),
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = recipient.Name,
            });
            labels.AddChild(new Label
            {
                Text = FormatLookupText(recipient),
                StyleClasses = { "LabelSubText" },
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = button.ToolTip,
            });
            row.AddChild(labels);
            button.AddChild(row);

            button.OnPressed += _ =>
            {
                if (_addingMembersToGroup is { } groupConversation)
                {
                    AddGroupMember?.Invoke(groupConversation, recipient.Number);
                    _addingMembersToGroup = null;
                    _viewMode = NanoChatViewMode.Settings;
                    Rebuild();
                }
                else if (GroupComposer.Visible)
                {
                    if (!_selectedGroupMembers.Contains(recipient.Number) &&
                        _selectedGroupMembers.Count >= NanoChatGroup.MaxMembers - 1)
                        return;

                    if (!_selectedGroupMembers.Add(recipient.Number))
                        _selectedGroupMembers.Remove(recipient.Number);
                    UpdateGroupComposer();
                    RebuildLookup();
                }
                else
                {
                    RequestNewChat(recipient);
                }
            };
            LookupList.AddChild(button);
        }

        if (!anyEntries)
            LookupList.AddChild(CreateDirectoryEmptyLabel());
    }

    private void RebuildChatList()
    {
        ChatList.RemoveAllChildren();

        var contacts = _state!.Recipients.Values.OrderBy(recipient => recipient.Name).ToList();
        var groups = _state.Groups.Values.OrderBy(group => group.Name).ToList();

        NoChatsLabel.Text = Loc.GetString("nanochat-no-chats");
        NoChatsLabel.Visible = contacts.Count == 0 && groups.Count == 0;

        if (contacts.Count == 0 && groups.Count == 0)
        {
            ChatList.AddChild(NoChatsLabel);
            return;
        }

        foreach (var recipient in contacts)
        {
            var conversation = new NanoChatConversationId(NanoChatConversationType.Direct, recipient.Number);
            ChatList.AddChild(CreateConversationButton(
                conversation,
                FormatDirectDisplayName(recipient.Name),
                recipient.Name,
                recipient.HasUnread));
        }

        foreach (var group in groups)
        {
            var conversation = new NanoChatConversationId(NanoChatConversationType.Group, group.Id);
            ChatList.AddChild(CreateConversationButton(
                conversation,
                group.Name,
                group.Name,
                group.HasUnread,
                CreateFixedIcon(GroupTexture, 19, 24, HAlignment.Left)));
        }
    }

    private Button CreateConversationButton(
        NanoChatConversationId conversation,
        string displayName,
        string fullName,
        bool unread,
        Control? icon = null)
    {
        var isSelected = GetActiveConversation() == conversation;
        var preview = GetLastMessagePreview(conversation);
        var button = new Button
        {
            HorizontalExpand = true,
            Pressed = isSelected,
            ToggleMode = true,
            ToolTip = fullName,
            ModulateSelfOverride = isSelected ? SelectedEntryColor : null,
        };
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(3, 2),
            SeparationOverride = icon == null ? 0 : 4,
        };
        if (icon != null)
            row.AddChild(icon);

        var labels = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
        labels.AddChild(new Label
        {
            Text = FormatListText(displayName),
            HorizontalExpand = true,
            ClipText = true,
            ToolTip = fullName,
        });
        labels.AddChild(new Label
        {
            Text = FormatListText(preview),
            StyleClasses = { "LabelSubText" },
            HorizontalExpand = true,
            ClipText = true,
            ToolTip = preview,
        });
        row.AddChild(labels);
        if (unread && !isSelected)
            row.AddChild(CreateUnreadDot());

        button.AddChild(row);
        button.OnPressed += _ =>
        {
            _selectedConversation = conversation;
            _viewMode = NanoChatViewMode.Chats;
            SelectConversation?.Invoke(conversation);
            Rebuild();
        };
        return button;
    }

    private void RebuildMessages()
    {
        var state = _state;
        if (state is null)
            return;

        MessageList.RemoveAllChildren();

        var activeConversation = GetActiveConversation();
        if (_deleteConfirmation != activeConversation)
            ResetDeleteConfirmation();

        var hasChats = state.Recipients.Count > 0 || state.Groups.Count > 0;
        var focusComposer = activeConversation is not null && !MessageInputContainer.Visible;
        WelcomeView.Visible = !hasChats;
        ChatView.Visible = hasChats;
        NoConversationSelectedView.Visible = hasChats && activeConversation is null;
        ConversationView.Visible = activeConversation is not null && _viewMode != NanoChatViewMode.Settings;
        ConversationSettingsView.Visible = activeConversation is not null && _viewMode == NanoChatViewMode.Settings;
        MessageInputContainer.Visible = activeConversation is not null;

        if (focusComposer)
            MessageInput.GrabKeyboardFocus();

        WelcomeTitle.Text = Loc.GetString("nanochat-welcome-title");
        WelcomeTitle.FontColorOverride = AccentColor;
        WelcomeDetails.Text = Loc.GetString("nanochat-welcome-details");
        WelcomeLookupButton.Text = Loc.GetString("nanochat-welcome-find-contact");
        NoConversationSelectedLabel.Text = Loc.GetString("nanochat-select-chat");
        NoConversationSelectedLabel.FontColorOverride = AccentColor;
        NoConversationSelectedDetails.Text = Loc.GetString("nanochat-select-chat-details");

        if (activeConversation is not { } current)
            return;

        if (current.Type == NanoChatConversationType.Direct)
        {
            var hasRecipient = state.Recipients.TryGetValue(current.Id, out var selectedRecipient);
            CurrentChatDetails.Text = hasRecipient && selectedRecipient.JobTitle is { } jobTitle
                ? $"{jobTitle} · #{current.Id:D4}"
                : $"#{current.Id:D4}";
            CurrentChatDetails.ToolTip = hasRecipient
                ? selectedRecipient.Name
                : Loc.GetString("nanochat-unknown-contact");
            DeleteChatButton.Visible = true;
        }
        else
        {
            var group = state.Groups[current.Id];
            CurrentChatDetails.Text = $"{group.Name} · {group.Members.Count}/{NanoChatGroup.MaxMembers}";
            CurrentChatDetails.ToolTip = group.Name;
            DeleteChatButton.Visible = false;
        }
        CurrentChatHeader.PanelOverride = HeaderPanel;
        CurrentChatHeader.ModulateSelfOverride = null;
        if (_deleteConfirmation == null)
            DeleteChatButton.ToolTip = Loc.GetString("nanochat-delete-chat");
        UpdateComposerState(MessageInput.Text);

        if (_lastRenderedConversation != current)
            RequestScrollToBottom();

        var messages = current.Type == NanoChatConversationType.Direct
            ? state.Messages.GetValueOrDefault(current.Id)
            : state.GroupMessages.GetValueOrDefault(current.Id);
        if (messages == null || messages.Count == 0)
        {
            MessageList.AddChild(new Label
            {
                Text = Loc.GetString("nanochat-no-messages"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(4),
                StyleClasses = { "LabelSubText" },
            });
            RequestScrollToBottom();
            return;
        }

        foreach (var message in messages)
        {
            var own = message.Sender == state.OwnNumber;
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };
            if (own)
                row.AddChild(new BoxContainer { HorizontalExpand = true });
            var card = new PanelContainer
            {
                MinWidth = 84,
                MaxWidth = MessageBubbleMaxWidth,
                Margin = new Thickness(1),
                PanelOverride = own ? OutgoingMessagePanel : IncomingMessagePanel,
                ModulateSelfOverride = own ? Color.FromHex("#C2D9E6") : Color.FromHex("#B8C0C9"),
                StyleClasses = { "AngleRect" },
            };
            var contents = new BoxContainer { Orientation = LayoutOrientation.Vertical, Margin = new Thickness(8, 6, 8, 5) };
            if (current.Type == NanoChatConversationType.Group && !own)
            {
                var senderName = state.Groups[current.Id].Members.TryGetValue(message.Sender, out var senderMember)
                    ? ShortenDisplayName(senderMember.Name)
                    : $"#{message.Sender:D4}";
                contents.AddChild(new Label
                {
                    Text = senderName,
                    StyleClasses = { "LabelSubText" },
                    FontColorOverride = AccentColor,
                    ClipText = true,
                    ToolTip = senderName,
                    Margin = new Thickness(0, 0, 0, 2),
                });
            }
            var messageLabel = new RichTextLabel
            {
                MaxWidth = MessageBubbleMaxWidth - 22f,
                HorizontalExpand = true,
            };
            messageLabel.SetMessage(
                FormattedMessage.FromMarkupPermissive(message.Content),
                UserFormattableTags.BaseAllowedTags,
                MessageTextColor);
            contents.AddChild(messageLabel);
            contents.AddChild(new Label
            {
                Text = FormatMessageStatus(message),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Right,
                FontColorOverride = DimTextColor,
                Margin = new Thickness(0, 3, 0, 0),
            });
            card.AddChild(contents);
            row.AddChild(card);
            if (!own)
                row.AddChild(new BoxContainer { HorizontalExpand = true });
            MessageList.AddChild(row);
        }

        _lastRenderedConversation = current;
    }

    private void SubmitMessage()
    {
        if (_state is null)
            return;

        var conversation = GetActiveConversation();
        var text = MessageInput.Text.Trim();
        var plainLength = FormattedMessage.RemoveMarkupPermissive(text).Trim().Length;

        if (conversation is null ||
            plainLength == 0 ||
            plainLength > NanoChatMessage.MaxLength ||
            text.Length > NanoChatMessage.MaxMarkupLength)
            return;

        SendMessage?.Invoke(conversation.Value, text);
        MessageInput.Clear();
        UpdateComposerState(string.Empty);
        RequestScrollToBottom();
    }

    private void UpdateComposerState(string text)
    {
        var length = FormattedMessage.RemoveMarkupPermissive(text).Length;
        var conversation = GetActiveConversation();
        var hasChat = conversation != null;
        var blocked = conversation is { Type: NanoChatConversationType.Direct } direct &&
                      _state?.BlockedNumbers.Contains(direct.Id) == true;
        var tooLong = length > NanoChatMessage.MaxLength || text.Length > NanoChatMessage.MaxMarkupLength;

        SendButton.Disabled = !hasChat || blocked || string.IsNullOrWhiteSpace(text) || tooLong;
        SendButton.ModulateSelfOverride = SendButton.Disabled
            ? Color.FromHex("#59616B")
            : Color.FromHex("#3F5C6C");
        CharacterCount.Visible = tooLong;
        if (tooLong)
            CharacterCount.Text = Loc.GetString("nanochat-message-too-long", ("current", length), ("max", NanoChatMessage.MaxLength));
    }

    private void SubmitStartChat()
    {
        if (!uint.TryParse(NumberInput.Text.Trim(), out var number) || number == _state?.OwnNumber)
            return;

        if (_addingMembersToGroup is { } groupConversation)
        {
            AddGroupMember?.Invoke(groupConversation, number);
            _addingMembersToGroup = null;
            _viewMode = NanoChatViewMode.Settings;
            NumberInput.Clear();
            Rebuild();
            return;
        }

        if (GroupComposer.Visible)
        {
            if (_selectedGroupMembers.Count >= NanoChatGroup.MaxMembers - 1)
                return;

            _selectedGroupMembers.Add(number);
            NumberInput.Clear();
            UpdateGroupComposer();
            RebuildLookup();
            return;
        }

        NanoChatRecipient? directoryEntry = null;
        if (_state?.Directory is { } directory)
        {
            foreach (var candidate in directory)
            {
                if (candidate.Number != number)
                    continue;

                directoryEntry = candidate;
                break;
            }
        }

        if (directoryEntry is { } knownContact)
        {
            RequestNewChat(knownContact);
            return;
        }

        _pendingNewChat = number;
        NewChat?.Invoke(number);
        UpdateStartChatState(NumberInput.Text);
    }

    private void UpdateStartChatState(string text)
    {
        StartChatButton.Disabled = _pendingNewChat != null ||
                                   !uint.TryParse(text.Trim(), out var number) ||
                                   number == _state?.OwnNumber ||
                                   GroupComposer.Visible && _selectedGroupMembers.Count >= NanoChatGroup.MaxMembers - 1;
    }

    private void RequestNewChat(NanoChatRecipient recipient)
    {
        if (_pendingNewChat != null)
            return;

        _pendingNewChat = recipient.Number;
        NewChat?.Invoke(recipient.Number);
        UpdateStartChatState(NumberInput.Text);
    }

    private string GetLastMessagePreview(NanoChatConversationId conversation)
    {
        var messages = GetMessages(_state!, conversation);
        if (messages is { Count: > 0 })
        {
            var message = messages[^1];
            var plain = FormattedMessage.RemoveMarkupPermissive(message.Content);
            return message.Sender == _state!.OwnNumber
                ? Loc.GetString("nanochat-message-preview-own", ("message", plain))
                : plain;
        }

        return Loc.GetString("nanochat-no-messages");
    }

    internal static string ShortenDisplayName(string name)
    {
        var firstName = name.Split(' ', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
        if (string.IsNullOrEmpty(firstName))
            return name;

        var hyphenParts = firstName.Split('-', StringSplitOptions.RemoveEmptyEntries);
        if (hyphenParts.Length > 2)
            return $"{hyphenParts[0]}-{hyphenParts[1]}";

        return firstName;
    }

    internal static string FormatDirectDisplayName(string name)
    {
        var parts = name.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
            return name;

        var firstName = ShortenDisplayName(parts[0]);
        if (parts.Length == 1)
            return firstName;

        var surname = parts[^1];
        return surname.Length == 0 ? firstName : $"{firstName} {surname[0]}.";
    }

    private static string FormatListText(string text)
    {
        const int maxCharacters = 28;
        return text.Length <= maxCharacters ? text : text[..(maxCharacters - 1)] + "…";
    }

    private static string FormatLookupText(NanoChatRecipient recipient)
    {
        var details = recipient.JobTitle is { Length: > 0 }
            ? $"{recipient.JobTitle} · #{recipient.Number:D4}"
            : $"#{recipient.Number:D4}";

        const int maxCharacters = 30;
        return details.Length <= maxCharacters ? details : details[..(maxCharacters - 1)] + "…";
    }

    private static Label CreateDirectoryEmptyLabel()
    {
        return new Label
        {
            Text = Loc.GetString("nanochat-directory-empty"),
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(4, 6),
            StyleClasses = { "LabelSubText" },
        };
    }

    private void SetGroupComposerVisible(bool visible)
    {
        GroupComposer.Visible = visible;
        if (!visible)
        {
            _selectedGroupMembers.Clear();
            NewGroupNameInput.Clear();
        }

        UpdateGroupComposer();
        RebuildLookup();
    }

    private void UpdateGroupComposer()
    {
        SelectedMembersCount.Text = $"{_selectedGroupMembers.Count + 1}/{NanoChatGroup.MaxMembers}";
        ConfirmCreateGroupButton.Text = Loc.GetString("nanochat-group-create");
        ConfirmCreateGroupButton.Disabled = _selectedGroupMembers.Count == 0 ||
                                            string.IsNullOrWhiteSpace(NewGroupNameInput.Text) ||
                                            FormattedMessage.RemoveMarkupPermissive(NewGroupNameInput.Text).Trim().Length > NanoChatGroup.MaxNameLength;
        NewGroupNameInput.PlaceHolder = Loc.GetString("nanochat-group-name-placeholder");
        DirectorySearchInput.PlaceHolder = Loc.GetString("nanochat-directory-search-placeholder");
    }

    private void SubmitCreateGroup()
    {
        var name = FormattedMessage.RemoveMarkupPermissive(NewGroupNameInput.Text).Trim();
        if (name.Length is 0 or > NanoChatGroup.MaxNameLength || _selectedGroupMembers.Count == 0)
            return;

        CreateGroup?.Invoke(name, _selectedGroupMembers.ToList());
        SetGroupComposerVisible(false);
        _viewMode = NanoChatViewMode.Chats;
    }

    private void RebuildConversationSettings()
    {
        if (_state is null || GetActiveConversation() is not { } conversation)
            return;

        WelcomeView.Visible = false;
        NoConversationSelectedView.Visible = false;
        ConversationView.Visible = false;
        ConversationSettingsView.Visible = true;
        ConversationSettingsList.RemoveAllChildren();

        if (conversation.Type == NanoChatConversationType.Direct)
        {
            RebuildDirectSettings(conversation);
            return;
        }

        RebuildGroupSettings(conversation);
    }

    private void RebuildDirectSettings(NanoChatConversationId conversation)
    {
        _groupNameDraftFor = null;
        if (_state == null || !_state.Recipients.TryGetValue(conversation.Id, out var recipient))
            return;

        SettingsTitle.Text = recipient.Name;
        GroupRenameRow.Visible = false;
        MuteConversationButton.Visible = false;
        DeleteGroupButton.Visible = false;
        LeaveOrBlockButton.Text = Loc.GetString(_state.BlockedNumbers.Contains(recipient.Number)
            ? "nanochat-unblock-contact"
            : "nanochat-block-contact");
        ConversationSettingsList.AddChild(CreatePersonRow(
            recipient.Name,
            recipient.JobTitle,
            recipient.Number,
            recipient.JobIcon));
    }

    private void RebuildGroupSettings(NanoChatConversationId conversation)
    {
        if (_state == null)
            return;

        if (!_state.Groups.TryGetValue(conversation.Id, out var group) ||
            !group.Members.TryGetValue(_state.OwnNumber, out var ownMember))
            return;

        SettingsTitle.Text = $"{group.Name} · {group.Members.Count}/{NanoChatGroup.MaxMembers}";
        GroupRenameRow.Visible = ownMember.IsAdmin;
        if (_groupNameDraftFor != group.Id)
        {
            GroupNameInput.Text = group.Name;
            _groupNameDraftFor = group.Id;
        }
        RenameGroupButton.Text = Loc.GetString("nanochat-group-rename");
        MuteConversationButton.Visible = true;
        MuteConversationButton.Text = Loc.GetString(group.NotificationsMuted
            ? "nanochat-group-unmute"
            : "nanochat-group-mute");
        LeaveOrBlockButton.Text = Loc.GetString("nanochat-group-leave");
        DeleteGroupButton.Visible = ownMember.IsAdmin;
        DeleteGroupButton.Text = Loc.GetString("nanochat-group-delete");

        if (ownMember.IsAdmin && group.Members.Count < NanoChatGroup.MaxMembers)
        {
            var addButton = new Button { Text = Loc.GetString("nanochat-group-add-member"), HorizontalExpand = true };
            addButton.OnPressed += _ =>
            {
                _addingMembersToGroup = conversation;
                _viewMode = NanoChatViewMode.Lookup;
                Rebuild();
            };
            ConversationSettingsList.AddChild(addButton);
        }

        foreach (var member in group.Members.Values.OrderByDescending(member => member.IsAdmin).ThenBy(member => member.Name))
            ConversationSettingsList.AddChild(CreateGroupMemberRow(conversation, member, ownMember.IsAdmin));
    }

    private Control CreateGroupMemberRow(
        NanoChatConversationId conversation,
        NanoChatGroupMember member,
        bool ownMemberIsAdmin)
    {
        var canManage = ownMemberIsAdmin && member.Number != _state?.OwnNumber;
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 3,
        };
        row.AddChild(CreatePersonRow(
            member.Name,
            member.JobTitle,
            member.Number,
            member.JobIcon,
            member.IsAdmin && !canManage));

        if (!canManage)
            return row;

        var removeButton = new Button
        {
            Text = "×",
            ToolTip = Loc.GetString("nanochat-group-remove-member"),
            MinSize = new Vector2i(28, 28),
            MaxSize = new Vector2i(28, 28),
        };
        removeButton.OnPressed += _ => RemoveGroupMember?.Invoke(conversation, member.Number);
        row.AddChild(removeButton);

        var adminButton = new Button
        {
            ToolTip = Loc.GetString(member.IsAdmin ? "nanochat-group-remove-admin" : "nanochat-group-make-admin"),
            ToggleMode = true,
            Pressed = member.IsAdmin,
            MinSize = new Vector2i(28, 28),
            MaxSize = new Vector2i(28, 28),
        };
        adminButton.AddChild(CreateInsetIcon(CrownTexture, 14, 4));
        adminButton.OnPressed += _ => SetGroupAdmin?.Invoke(conversation, member.Number, !member.IsAdmin);
        row.AddChild(adminButton);
        return row;
    }

    private Control CreatePersonRow(
        string name,
        string? job,
        uint number,
        ProtoId<JobIconPrototype> jobIcon,
        bool admin = false)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 4,
            Margin = new Thickness(4, 2),
        };
        row.AddChild(CreateJobIcon(jobIcon));
        var labels = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
        var nameRow = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, SeparationOverride = 3 };
        nameRow.AddChild(new Label
        {
            Text = name,
            HorizontalExpand = true,
            ClipText = true,
            ToolTip = name,
        });
        if (admin)
            nameRow.AddChild(CreateInsetIcon(CrownTexture, 14, 4));
        labels.AddChild(nameRow);
        labels.AddChild(new Label
        {
            Text = job is { Length: > 0 } ? $"{job} · #{number:D4}" : $"#{number:D4}",
            StyleClasses = { "LabelSubText" },
            ClipText = true,
        });
        row.AddChild(labels);
        return row;
    }

    private Control CreateJobIcon(ProtoId<JobIconPrototype> jobIcon)
    {
        var icon = new TextureRect
        {
            MinSize = new Vector2i(20, 20),
            MaxSize = new Vector2i(20, 20),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Center,
        };
        if (_prototypeManager.TryIndex(jobIcon, out var prototype))
            icon.Texture = _spriteSystem.Frame0(prototype.Icon);

        var slot = new Control
        {
            MinSize = new Vector2i(24, 20),
            MaxSize = new Vector2i(24, 20),
            VerticalAlignment = VAlignment.Center,
        };
        slot.AddChild(icon);
        return slot;
    }

    private static Control CreateFixedIcon(
        string texturePath,
        int iconSize,
        int slotWidth,
        HAlignment alignment = HAlignment.Center)
    {
        var slot = new Control
        {
            MinSize = new Vector2i(slotWidth, iconSize),
            MaxSize = new Vector2i(slotWidth, iconSize),
            VerticalAlignment = VAlignment.Center,
        };
        var icon = CreateStaticIcon(texturePath, iconSize);
        icon.HorizontalAlignment = alignment;
        slot.AddChild(icon);
        return slot;
    }

    private static Control CreateInsetIcon(string texturePath, int iconSize, int rightInset)
    {
        var slot = new Control
        {
            MinSize = new Vector2i(iconSize + rightInset, iconSize),
            MaxSize = new Vector2i(iconSize + rightInset, iconSize),
            VerticalAlignment = VAlignment.Center,
        };
        var icon = CreateStaticIcon(texturePath, iconSize);
        icon.HorizontalAlignment = HAlignment.Left;
        slot.AddChild(icon);
        return slot;
    }

    private static TextureRect CreateStaticIcon(string texturePath, int size)
        => new()
        {
            TexturePath = texturePath,
            MinSize = new Vector2i(size, size),
            MaxSize = new Vector2i(size, size),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            CanShrink = true,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore,
        };

    private static PanelContainer CreateUnreadDot()
        => new()
        {
            MinSize = new Vector2i(6, 6),
            MaxSize = new Vector2i(6, 6),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(4, 0, 0, 0),
            PanelOverride = new StyleBoxFlat { BackgroundColor = AccentColor },
        };

    private void SubmitRenameGroup()
    {
        if (GetActiveConversation() is not { Type: NanoChatConversationType.Group } conversation)
            return;
        var name = FormattedMessage.RemoveMarkupPermissive(GroupNameInput.Text).Trim();
        if (name.Length is 0 or > NanoChatGroup.MaxNameLength)
            return;
        RenameGroup?.Invoke(conversation, name);
    }

    private void ToggleCurrentConversationMute()
    {
        if (GetActiveConversation() is { Type: NanoChatConversationType.Group } conversation)
            ToggleGroupMute?.Invoke(conversation);
    }

    private void LeaveOrBlockCurrentConversation()
    {
        if (_state is null || GetActiveConversation() is not { } conversation)
            return;

        if (conversation.Type == NanoChatConversationType.Group)
        {
            LeaveGroup?.Invoke(conversation);
            _selectedConversation = null;
            _viewMode = NanoChatViewMode.Chats;
            return;
        }

        SetBlocked?.Invoke(conversation.Id, !_state.BlockedNumbers.Contains(conversation.Id));
    }

    private void DeleteCurrentGroup()
    {
        if (GetActiveConversation() is not { Type: NanoChatConversationType.Group } conversation)
            return;

        if (_deleteConfirmation != conversation)
        {
            _deleteConfirmation = conversation;
            DeleteGroupButton.Text = Loc.GetString("nanochat-group-delete-confirm");
            DeleteGroupButton.ModulateSelfOverride = Color.FromHex("#C95C5C");
            return;
        }

        DeleteGroup?.Invoke(conversation);
        _selectedConversation = null;
        _viewMode = NanoChatViewMode.Chats;
        ResetDeleteConfirmation();
    }

    private void ResetDeleteConfirmation()
    {
        _deleteConfirmation = null;
        DeleteChatButton.ToolTip = Loc.GetString("nanochat-delete-chat");
        DeleteChatButton.ModulateSelfOverride = null;
        DeleteGroupButton.ModulateSelfOverride = null;
        DeleteGroupButton.Text = Loc.GetString("nanochat-group-delete");
    }

    private static StyleBoxFlat CreatePanelStyle(string background, Color border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = border,
            BorderThickness = new Thickness(1),
        };
    }

    private void RequestScrollToBottom()
    {
        _scrollToBottom = true;
    }

    private bool ShouldFollowBottom(NanoChatUiState nextState)
    {
        var previousState = _state;
        var previousConversation = _selectedConversation ?? (previousState == null ? null : GetStateConversation(previousState));
        var nextConversation = _selectedConversation ?? GetStateConversation(nextState);

        if (nextConversation == null)
            return previousConversation != null;

        if (previousConversation != nextConversation)
            return true;

        if (previousState == null)
            return true;

        var previousMessages = GetMessages(previousState, nextConversation.Value);
        var nextMessages = GetMessages(nextState, nextConversation.Value);

        if (!HasNewLatestMessage(previousMessages, nextMessages))
            return false;

        var latestMessage = nextMessages![^1];
        var viewportBottom = MessagesScroll.VScrollTarget + MessagesScroll.Size.Y;
        return ShouldFollowNewMessage(
            latestMessage.Sender,
            nextState.OwnNumber,
            MessageList.Size.Y,
            viewportBottom);
    }

    /// <summary>
    ///     Detects a newly appended message by identity instead of list length. Once a page is full,
    ///     the server sends a sliding window whose size stays constant while its newest item changes.
    /// </summary>
    internal static bool HasNewLatestMessage(
        IReadOnlyList<NanoChatMessage>? previousMessages,
        IReadOnlyList<NanoChatMessage>? nextMessages)
    {
        if (nextMessages is not { Count: > 0 })
            return false;

        return previousMessages is not { Count: > 0 } ||
               !nextMessages[^1].Equals(previousMessages[^1]);
    }

    /// <summary>
    ///     Decides whether a new message should move the viewport. The dimensions must describe the
    ///     existing list before it is rebuilt, so an incoming message cannot change this decision.
    /// </summary>
    internal static bool ShouldFollowNewMessage(
        uint sender,
        uint ownNumber,
        float contentHeight,
        float viewportBottom)
    {
        if (sender == ownNumber)
            return true;

        return contentHeight - viewportBottom <= FollowBottomThreshold;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!MessagesScroll.Visible)
            return;

        if (_restoreScrollAfterPrepend)
        {
            if (!MessageList.IsMeasureValid || !MessagesScroll.IsArrangeValid)
                return;

            _restoreScrollAfterPrepend = false;
            MessagesScroll.VScrollTarget = Math.Max(0, MessageList.Size.Y - _historyHeightBeforeLoad);
            return;
        }

        if (!_scrollToBottom)
            return;

        // UI frame updates run before queued layout updates. Keep the request until the newly
        // rebuilt message list has been measured and the scroll range reflects its final height.
        if (!MessageList.IsMeasureValid || !MessagesScroll.IsArrangeValid)
            return;

        _scrollToBottom = false;
        MessagesScroll.VScrollTarget = float.PositiveInfinity;
    }

    private void TryLoadOlderMessages()
    {
        if (_loadingOlder || MessagesScroll.VScrollTarget > 2f || GetActiveConversation() is not { } conversation ||
            _state?.HasOlderMessages.Contains(conversation) != true)
            return;

        _loadingOlder = true;
        _historyHeightBeforeLoad = MessageList.Size.Y;
        LoadOlderMessages?.Invoke(conversation);
    }

    private NanoChatConversationId? GetActiveConversation()
    {
        if (_selectedConversation is { } selected)
            return selected;
        return _state == null ? null : GetStateConversation(_state);
    }

    private static NanoChatConversationId? GetStateConversation(NanoChatUiState state)
    {
        if (state.CurrentGroup is { } group)
            return new NanoChatConversationId(NanoChatConversationType.Group, group);
        if (state.CurrentChat is { } chat)
            return new NanoChatConversationId(NanoChatConversationType.Direct, chat);
        return null;
    }

    private static bool HasConversation(NanoChatUiState state, NanoChatConversationId conversation)
        => conversation.Type == NanoChatConversationType.Direct
            ? state.Recipients.ContainsKey(conversation.Id)
            : state.Groups.ContainsKey(conversation.Id);

    private static List<NanoChatMessage>? GetMessages(NanoChatUiState state, NanoChatConversationId conversation)
        => conversation.Type == NanoChatConversationType.Direct
            ? state.Messages.GetValueOrDefault(conversation.Id)
            : state.GroupMessages.GetValueOrDefault(conversation.Id);

    private static string FormatMessageStatus(NanoChatMessage message)
    {
        var time = message.Timestamp.ToString(@"hh\:mm");
        if (message.IntendedRecipients > 0 && message.DeliveredRecipients < message.IntendedRecipients)
            return message.DeliveredRecipients == 0
                ? Loc.GetString("nanochat-message-status-failed", ("time", time))
                : Loc.GetString("nanochat-message-status-partial",
                    ("time", time),
                    ("delivered", message.DeliveredRecipients),
                    ("total", message.IntendedRecipients));
        return message.DeliveryFailed
            ? Loc.GetString("nanochat-message-status-failed", ("time", time))
            : time;
    }

    private static bool CanKeepRenderedConversation(
        NanoChatUiState previous,
        NanoChatUiState next,
        NanoChatConversationId conversation)
    {
        if (!HasConversation(previous, conversation) || !HasConversation(next, conversation))
            return false;

        if (conversation.Type == NanoChatConversationType.Direct)
        {
            var oldRecipient = previous.Recipients[conversation.Id];
            var newRecipient = next.Recipients[conversation.Id];
            if (oldRecipient.Name != newRecipient.Name || oldRecipient.JobTitle != newRecipient.JobTitle)
                return false;
        }
        else
        {
            var oldGroup = previous.Groups[conversation.Id];
            var newGroup = next.Groups[conversation.Id];
            if (oldGroup.Name != newGroup.Name ||
                oldGroup.Members.Count != newGroup.Members.Count ||
                oldGroup.Members.Any(pair =>
                    !newGroup.Members.TryGetValue(pair.Key, out var member) ||
                    pair.Value.Name != member.Name))
                return false;
        }

        var previousMessages = GetMessages(previous, conversation);
        var nextMessages = GetMessages(next, conversation);
        if (previousMessages == null || nextMessages == null)
            return previousMessages == nextMessages;

        return previousMessages.SequenceEqual(nextMessages);
    }
}
