using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.Passports.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ChameleonPassportWindow : DefaultWindow
    {
        public event Action<string>? OnNameChanged;
        public event Action<string>? OnSpeciesChanged;
        public event Action<string>? OnGenderChanged;
        public event Action<string>? OnDateOfBirthChanged;
        public event Action<string>? OnHeightChanged;
        public event Action<string>? OnPIDChanged;

        public ChameleonPassportWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            NameLineEdit.OnTextEntered += e => OnNameChanged?.Invoke(e.Text);
            NameLineEdit.OnFocusExit += e => OnNameChanged?.Invoke(e.Text);

            SpeciesLineEdit.OnTextEntered += e => OnSpeciesChanged?.Invoke(e.Text);
            SpeciesLineEdit.OnFocusExit += e => OnSpeciesChanged?.Invoke(e.Text);

            GenderLineEdit.OnTextEntered += e => OnGenderChanged?.Invoke(e.Text);
            GenderLineEdit.OnFocusExit += e => OnGenderChanged?.Invoke(e.Text);

            DateOfBirthLineEdit.OnTextEntered += e => OnDateOfBirthChanged?.Invoke(e.Text);
            DateOfBirthLineEdit.OnFocusExit += e => OnDateOfBirthChanged?.Invoke(e.Text);

            HeightLineEdit.OnTextEntered += e => OnHeightChanged?.Invoke(e.Text);
            HeightLineEdit.OnFocusExit += e => OnHeightChanged?.Invoke(e.Text);

            PIDLineEdit.OnTextEntered += e => OnPIDChanged?.Invoke(e.Text);
            PIDLineEdit.OnFocusExit += e => OnPIDChanged?.Invoke(e.Text);
        }

        public void SetCurrentName(string name)
        {
            NameLineEdit.Text = name;
        }

        public void SetCurrentSpecies(string species)
        {
            SpeciesLineEdit.Text = species;
        }

        public void SetCurrentGender(string gender)
        {
            GenderLineEdit.Text = gender;
        }

        public void SetCurrentDateOfBirth(string dateOfBirth)
        {
            DateOfBirthLineEdit.Text = dateOfBirth;
        }

        public void SetCurrentHeight(string height)
        {
            HeightLineEdit.Text = height;
        }

        public void SetCurrentPID(string pid)
        {
            PIDLineEdit.Text = pid;
        }
    }
}
