- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  subnames:
  - Male: администратор ИВС
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 50h # Corvax-RoleTime
    - !type:AgeRequirement
      age: 6 # WL-Changes-AgeRequirement
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  # WL-Skills-start
  bonusSkillPoints: 10
  defaultSkills:
    Bureaucracy: 3
    Eva: 3
    Forensics: 2
    Combat: 2
    Weapons: 3
  # WL-Skills-end

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
