using System.Linq;
using System.Numerics;
using Content.Client._WL.Barks;
using Content.Client.Stylesheets;
using Content.Shared._WL.Barks;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WL.Barks.UI;

[GenerateTypedNameReferences]
public sealed partial class BarkTab : Control
{
    private static readonly (string Name, string[] Categories)[] CategoryGroups =
    [
        ("humanoid-profile-editor-bark-group-general", ["standard", "voice", "synth"]),
        ("humanoid-profile-editor-bark-group-undertale", ["undertale", "undertale_yellow", "deltarune", "deltarune_rewritten", "underswap"]),
        ("humanoid-profile-editor-bark-group-games", ["minecraft", "dont_starve", "ace_attorney", "banjo_kazooie"]),
        ("humanoid-profile-editor-bark-group-stations", ["goon_station", "citadel_station"]),
        ("humanoid-profile-editor-bark-group-other", ["other"]),
    ];

    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly SpeechBarksSystem _barkSystem;

    private List<BarkPrototype> _allBarks = new();
    private List<BarkPrototype> _filteredBarks = new();
    private Dictionary<string, List<BarkPrototype>> _barksByCategory = new();
    private readonly Dictionary<Button, string?> _categoryButtons = new();
    private readonly Dictionary<Button, string> _barkButtons = new();
    private string? _selectedCategory = null;
    private string _currentBarkId = "";
    private float _currentPitch = SpeechBarksComponent.DefaultPitch;
    private float _currentMinVar = SpeechBarksComponent.DefaultMinDelay;
    private float _currentMaxVar = SpeechBarksComponent.DefaultMaxDelay;
    private bool _updatingSettings;

    public event Action<string>? OnBarkSelected;
    public event Action<float>? OnPitchChanged;
    public event Action<float>? OnMinVarChanged;
    public event Action<float>? OnMaxVarChanged;

    public BarkTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _barkSystem = IoCManager.Resolve<IEntityManager>().System<SpeechBarksSystem>();

        SearchEdit.OnTextChanged += OnSearchTextChanged;
        PitchEdit.OnTextEntered += OnPitchTextCommitted;
        PitchEdit.OnFocusExit += OnPitchTextCommitted;
        DelayVariationMinEdit.OnTextEntered += OnMinVarTextCommitted;
        DelayVariationMinEdit.OnFocusExit += OnMinVarTextCommitted;
        DelayVariationMaxEdit.OnTextEntered += OnMaxVarTextCommitted;
        DelayVariationMaxEdit.OnFocusExit += OnMaxVarTextCommitted;
        PreviewTextEdit.Text = Loc.GetString("humanoid-profile-editor-bark-preview-text-sample");
        PreviewTextEdit.OnTextEntered += _ => PlayCurrentBark();
        PreviewButton.OnPressed += _ => PlayCurrentBark();
        ResetButton.OnPressed += _ => ResetSettings();

        LoadBarks();
    }

    public void SetSelectedBark(string barkId, float pitch, float minVar, float maxVar)
    {
        _currentBarkId = barkId;
        SetSettings(pitch, minVar, maxVar, false);

        UpdateBarkButtons();
        UpdateSelectedBarkLabel();
    }

    private void LoadBarks()
    {
        _allBarks = _prototypeManager
            .EnumeratePrototypes<BarkPrototype>()
            .Where(b => b.RoundStart)
            .OrderBy(b => Loc.GetString(b.Name))
            .ToList();
        _barksByCategory = _allBarks
            .GroupBy(b => GetDisplayCategory(b.Category))
            .ToDictionary(g => g.Key, g => g.ToList());

        BuildCategoryButtons();
        SelectCategory(null);
    }

    private void BuildCategoryButtons()
    {
        CategoriesContainer.RemoveAllChildren();
        _categoryButtons.Clear();

        var allButton = new Button
        {
            Text = Loc.GetString("humanoid-profile-editor-bark-all"),
            ToggleMode = true,
            StyleClasses = { StyleClass.ButtonOpenRight },
            HorizontalExpand = true,
        };
        allButton.OnPressed += _ => SelectCategory(null);
        _categoryButtons.Add(allButton, null);
        CategoriesContainer.AddChild(allButton);

        var remainingCategories = _barksByCategory.Keys.ToHashSet();
        foreach (var (groupName, categories) in CategoryGroups)
        {
            var visibleCategories = categories
                .Where(remainingCategories.Contains)
                .ToList();
            if (visibleCategories.Count == 0)
                continue;

            CategoriesContainer.AddChild(new Label
            {
                Text = Loc.GetString(groupName),
                StyleClasses = { StyleClass.LabelSubText },
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Margin = new Thickness(4, 8, 4, 3),
            });

            foreach (var category in visibleCategories)
            {
                AddCategoryButton(category);
                remainingCategories.Remove(category);
            }
        }

        foreach (var category in remainingCategories.OrderBy(GetCategoryName))
            AddCategoryButton(category);
    }

    private void AddCategoryButton(string category)
    {
        var button = new Button
        {
            Text = GetCategoryName(category),
            ToggleMode = true,
            StyleClasses = { StyleClass.ButtonOpenRight },
            HorizontalExpand = true,
        };
        button.OnPressed += _ => SelectCategory(category);
        _categoryButtons.Add(button, category);
        CategoriesContainer.AddChild(button);
    }

    private void SelectCategory(string? category)
    {
        _selectedCategory = category;
        var displayName = category == null
            ? Loc.GetString("humanoid-profile-editor-bark-all")
            : GetCategoryName(category);

        foreach (var (button, buttonCategory) in _categoryButtons)
            button.Pressed = buttonCategory == category;

        SelectedCategoryLabel.Text = displayName;
        FilterBarks();
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        FilterBarks();
    }

    private void OnPitchTextCommitted(LineEdit.LineEditEventArgs args)
    {
        if (_updatingSettings)
            return;

        if (!float.TryParse(args.Text, out var pitch) || !float.IsFinite(pitch))
        {
            PitchEdit.Text = _currentPitch.ToString("F2");
            return;
        }

        pitch = SpeechBarksComponent.SanitizePitch(pitch);
        PitchEdit.Text = pitch.ToString("F2");
        if (pitch == _currentPitch)
            return;

        _currentPitch = pitch;
        OnPitchChanged?.Invoke(pitch);
    }

    private void OnMinVarTextCommitted(LineEdit.LineEditEventArgs args)
    {
        if (_updatingSettings)
            return;

        if (!float.TryParse(args.Text, out var minVar) || !float.IsFinite(minVar))
        {
            DelayVariationMinEdit.Text = _currentMinVar.ToString("F2");
            return;
        }

        minVar = Math.Clamp(minVar, SpeechBarksComponent.MinDelayLimit, _currentMaxVar);
        DelayVariationMinEdit.Text = minVar.ToString("F2");
        if (minVar == _currentMinVar)
            return;

        _currentMinVar = minVar;
        OnMinVarChanged?.Invoke(minVar);
    }

    private void OnMaxVarTextCommitted(LineEdit.LineEditEventArgs args)
    {
        if (_updatingSettings)
            return;

        if (!float.TryParse(args.Text, out var maxVar) || !float.IsFinite(maxVar))
        {
            DelayVariationMaxEdit.Text = _currentMaxVar.ToString("F2");
            return;
        }

        maxVar = Math.Clamp(maxVar, _currentMinVar, SpeechBarksComponent.MaxDelayLimit);
        DelayVariationMaxEdit.Text = maxVar.ToString("F2");
        if (maxVar == _currentMaxVar)
            return;

        _currentMaxVar = maxVar;
        OnMaxVarChanged?.Invoke(maxVar);
    }

    private void ResetSettings()
    {
        _barkSystem.StopPreview();
        PreviewTextEdit.Text = Loc.GetString("humanoid-profile-editor-bark-preview-text-sample");
        SetSettings(
            SpeechBarksComponent.DefaultPitch,
            SpeechBarksComponent.DefaultMinDelay,
            SpeechBarksComponent.DefaultMaxDelay,
            true);
    }

    private void SetSettings(float pitch, float minVar, float maxVar, bool notify)
    {
        pitch = SpeechBarksComponent.SanitizePitch(pitch);
        (minVar, maxVar) = SpeechBarksComponent.SanitizeDelays(minVar, maxVar);

        _currentPitch = pitch;
        _currentMinVar = minVar;
        _currentMaxVar = maxVar;

        _updatingSettings = true;
        PitchEdit.Text = pitch.ToString("F2");
        DelayVariationMinEdit.Text = minVar.ToString("F2");
        DelayVariationMaxEdit.Text = maxVar.ToString("F2");
        _updatingSettings = false;

        if (!notify)
            return;

        OnPitchChanged?.Invoke(pitch);
        OnMinVarChanged?.Invoke(minVar);
        OnMaxVarChanged?.Invoke(maxVar);
    }

    private void FilterBarks()
    {
        var searchText = SearchEdit.Text.ToLowerInvariant();
        IEnumerable<BarkPrototype> barks;
        if (_selectedCategory != null)
        {
            barks = _barksByCategory.GetValueOrDefault(_selectedCategory, new List<BarkPrototype>());
        }
        else
        {
            barks = _allBarks;
        }
        if (!string.IsNullOrWhiteSpace(searchText))
        {
            barks = barks.Where(b =>
                Loc.GetString(b.Name).ToLowerInvariant().Contains(searchText) ||
                b.ID.ToLowerInvariant().Contains(searchText));
        }

        _filteredBarks = barks.ToList();
        ResultsLabel.Text = Loc.GetString(
            "humanoid-profile-editor-bark-results",
            ("count", _filteredBarks.Count));

        BuildBarkButtons();
    }

    private void BuildBarkButtons()
    {
        BarksGrid.RemoveAllChildren();
        _barkButtons.Clear();

        foreach (var bark in _filteredBarks)
        {
            var button = new Button
            {
                Text = Loc.GetString(bark.Name),
                ToggleMode = true,
                HorizontalExpand = true,
                VerticalExpand = false,
                Margin = new Thickness(2),
                Pressed = bark.ID == _currentBarkId,
            };

            button.OnPressed += _ => OnBarkButtonPressed(bark.ID);
            _barkButtons.Add(button, bark.ID);
            BarksGrid.AddChild(button);
        }
    }

    private void OnBarkButtonPressed(string barkId)
    {
        _currentBarkId = barkId;
        OnBarkSelected?.Invoke(barkId);
        UpdateBarkButtons();
        UpdateSelectedBarkLabel();
        PlayCurrentBark();
    }

    private void UpdateBarkButtons()
    {
        foreach (var (button, barkId) in _barkButtons)
            button.Pressed = barkId == _currentBarkId;
    }

    private void UpdateSelectedBarkLabel()
    {
        var selected = _allBarks.FirstOrDefault(bark => bark.ID == _currentBarkId);
        var name = selected == null
            ? Loc.GetString("humanoid-profile-editor-bark-none")
            : Loc.GetString(selected.Name);

        SelectedBarkLabel.Text = Loc.GetString(
            "humanoid-profile-editor-bark-selected",
            ("name", name));
        PreviewButton.Disabled = selected == null;
    }

    private void PlayCurrentBark()
    {
        if (_allBarks.All(bark => bark.ID != _currentBarkId))
            return;

        _barkSystem.PlayDataPreview(
            _currentBarkId,
            _currentPitch,
            _currentMinVar,
            _currentMaxVar,
            PreviewTextEdit.Text);
    }

    private static string GetDisplayCategory(string category)
    {
        return category switch
        {
            "bluemoon_undertale" => "undertale",
            "bluemoon_deltarune" => "deltarune",
            "bluemoon_dont_starve" => "dont_starve",
            "bluemoon_goon" => "goon_station",
            "bluemoon_ace_attorney" => "ace_attorney",
            "bluemoon_banjo_kazooie" => "banjo_kazooie",
            "bluemoon_citadel" => "citadel_station",
            "bluemoon_other" => "other",
            "openbarks_voice" => "voice",
            "openbarks_synth" => "synth",
            _ => category,
        };
    }

    private static string GetCategoryName(string category)
    {
        return Loc.TryGetString($"bark-category-{category}", out var localized)
            ? localized
            : category;
    }
}
