using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Client.RichText;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.RichText;
using Content.Shared.Construction.Components;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Materials;
using Content.Shared._WL.Research;
using Content.Shared._WL.Research.Components;
using Content.Shared._WL.Research.Prototypes;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DAnalyzerMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private EntityUid _owner;

    public static readonly EntProtoId EmptyEffectId = "DAnalyzerEmptyEffect";

    private EntProtoId _currentObject = EmptyEffectId;

    private DAnalyzeState _currentState = DAnalyzeState.Invalid;

    public event Action<DAnalyzeType>? ButtonPressed;

    public DAnalyzerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AnalyzeButton.OnPressed += _ => ButtonPressed?.Invoke(DAnalyzeType.Analyze);
        DAnalyzeButton.OnPressed += _ => ButtonPressed?.Invoke(DAnalyzeType.DAnalyze);
        DestructButton.OnPressed += _ => ButtonPressed?.Invoke(DAnalyzeType.Destruct);
    }

    public void UpdateState(DAnalyzerBoundUserInterfaceState state)
    {
        _currentObject = state.ObjectId ?? EmptyEffectId;
        _currentState = state.ObjectId is null ? DAnalyzeState.Invalid : state.ObjectState;

        var isWorking = _currentState == DAnalyzeState.Analyzing || _currentState == DAnalyzeState.DAnalyzing;
        var canAnalyze = _currentState == DAnalyzeState.NotAnalyzed;
        var canDAnalyze = _currentState == DAnalyzeState.Analyzed;

        AnalyzeButton.Visible = canAnalyze && !isWorking;
        DAnalyzeButton.Visible = canDAnalyze && !isWorking;
        DestructButton.Visible = canDAnalyze && !isWorking;

        ObjectSprite.SetPrototype(_currentObject);

        switch (_currentState)
        {
            case DAnalyzeState.Invalid:
                DataLabel.Text = "EXOTIC BUTTERS";
                StatusLabel.Text = Loc.GetString("danalyzer-ui-status", ("status", "danalyzer-ui-status-invalid"));
                break;

            case DAnalyzeState.NotAnalyzed:
                DataLabel.Text = "EXOTIC BUTTERS 2";
                StatusLabel.Text = Loc.GetString("danalyzer-ui-status", ("status", "danalyzer-ui-status-notanalyzed"));
                break;

            case DAnalyzeState.Analyzing:
                DataLabel.Text = "EXOTIC BUTTERS 2";
                StatusLabel.Text = Loc.GetString("danalyzer-ui-status", ("status", "danalyzer-ui-status-analyzing"));
                break;

            case DAnalyzeState.Analyzed:
                DataLabel.Text = "EXOTIC BUTTERS 3";
                StatusLabel.Text = Loc.GetString("danalyzer-ui-status", ("status", "danalyzer-ui-status-analyzed"));
                break;

            case DAnalyzeState.DAnalyzing:
                DataLabel.Text = "EXOTIC BUTTERS 3";
                StatusLabel.Text = Loc.GetString("danalyzer-ui-status", ("status", "danalyzer-ui-status-danalyzing"));
                break;

            case DAnalyzeState.DAnalyzed:
                DataLabel.Text = "EXOTIC BUTTERS 2";
                StatusLabel.Text = Loc.GetString("danalyzer-ui-status", ("status", "danalyzer-ui-status-danalyzed"));
                break;
        }
    }
}
