using Content.Shared.Research.Prototypes;
using Content.Shared._WL.Research.Prototypes;
using Content.Shared._WL.Research.Components;
using Content.Shared.Containers.ItemSlots;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Timing;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DataStorageControl : Control
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    private readonly ItemSlotsSystem _itemSlots;

    private EntityUid? _owner;

    private EntityUid? _disk;

    public static readonly EntProtoId NoDiskEffectId = "DataReaderNoDiskEffect";
    // public Action? OnPressed;

    public DataStorageControl()//ResearchPrototype researchProto, ResearchState researchState, IPrototypeManager prototypeManager, SpriteSystem spriteSys, float time)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _itemSlots = _entityManager.System<ItemSlotsSystem>();
        /*

        var discipline = prototypeManager.Index<TechDisciplinePrototype>(researchProto.Discipline);
        //Background.PanelOverride.BorderColor = discipline.Color;

        ResearchName.Text = researchProto.LocalizedName;
        ResearchIcon.Texture = spriteSys.Frame0(researchProto.Icon);

        if (true)
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");

        MainBar.MinValue = 0f;
        MainBar.MaxValue = (float)researchState.PackagesCostModed;
        MainBar.Value = (float)researchState.ResearchedPackages;
        MainBar.SetTime(time);

        ResearchProgress.Text = $"{MainBar.Value}/{MainBar.MaxValue}";

        switch (researchState.Status)
        {
            case ResearchStatus.NotResearched:
                break;
        }

        //ResearchButton.Disabled = points < technology.Cost || !hasAccess;
        ResearchButton.OnPressed += _ => OnPressed?.Invoke();
        */
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        SetDisk(_disk);

        if (_owner == null)
            return;

        if (!_entityManager.TryGetComponent<DataReaderComponent>(_owner, out var reader) ||
            !_itemSlots.TryGetSlot(_owner.Value, reader.SlotId, out var itemSlot))
            return;

        if (_disk == itemSlot.Item)
            return;

        _disk = itemSlot.Item;
    }

    private void SetDisk(EntityUid? disk)
    {
        if (disk is null)
        {
            DiskSprite.SetPrototype(NoDiskEffectId);
            FormatButton.Disabled = true;
            FormatLabel.Visible = false;
            SizeLabel.Visible = false;

            DiskName.Text = "Диск отсутствует!";
            return;
        }

        DiskSprite.SetEntity(disk);

        if (!_entityManager.TryGetComponent<DataStorageComponent>(disk, out var storage))
        {
            FormatButton.Disabled = true;
            FormatLabel.Visible = false;
            SizeLabel.Visible = false;

            DiskName.Text = "Это чайник.";
            return;
        }

        FormatButton.Disabled = false;
        FormatLabel.Visible = true;
        SizeLabel.Visible = true;

        DiskName.Text = storage.Name;

        var formatProto = _protoMan.Index(storage.CurrentStorageFormat);
        FormatLabel.Text = formatProto.LocalizedName;
        FormatLabel.FontColorOverride = formatProto.Color;

        SizeLabel.Text = $"{storage.ExpiredSize} / {storage.Size}";
    }
}
