using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Client.RichText;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.RichText;
using Content.Shared.Construction.Components;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Materials;
using Content.Shared._WL.Research;
using Content.Shared._WL.Research.Components;
using Content.Shared._WL.Research.Prototypes;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class PointsDataReadMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    /*
    private readonly ItemSlotsSystem _itemSlots;
    private readonly FlatpackSystem _flatpack;
    private readonly MaterialStorageSystem _materialStorage;
    */

    private EntityUid _owner;

    private ResearchPointsSpecifier _points = new();

    private ResearchPointsSpecifier _maxPointsStorage = new();
    private ResearchPointsSpecifier _maxPointsDisk = new();

    public static readonly EntProtoId NoBoardEffectId = "FlatpackerNoBoardEffect";

    public static readonly Color NoPointsColor = Color.FromHex("#222222");

    public event Action<ResearchPointsSpecifier, bool>? TransferButtonPressed;

    public PointsDataReadMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ButtonTransfer.StyleClasses.Add(StyleClass.ButtonOpenLeft);
        ButtonTransfer.StyleClasses.Add(StyleClass.Positive);

        ButtonTransfer.OnPressed += OnTransfer;

        ButtonMinimum.OnPressed += OnMinimum;
        ButtonMaximum.OnPressed += OnMaximum;

        /*
        _itemSlots = _entityManager.System<ItemSlotsSystem>();
        _flatpack = _entityManager.System<FlatpackSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();


        InsertLabel.SetMarkup(Loc.GetString("flatpacker-ui-insert-board"));
        */
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
        DataStorageCard.SetOwner(uid);
    }

    public void UpdatePoints(PointsDataReadBoundUserInterfaceState state)
    {
        PointsLabels.Children.Clear();
        StoragePoints.Children.Clear();
        PointsSpins.Children.Clear();
        DiskPoints.Children.Clear();

        _points = new();
        _maxPointsStorage = new();
        _maxPointsDisk = new();

        foreach (var (key, value) in state.StoragePointsData.PointsDict)
        {
            var diskPointsExist = state.DiskPointsData.PointsDict.TryGetValue(key, out var diskDictValue);
            var diskValue = diskPointsExist ? diskDictValue : FixedPoint2.New(0);

            _points.PointsDict.Add(key, 0);

            _maxPointsStorage.PointsDict.Add(key, value);
            _maxPointsDisk.PointsDict.Add(key, diskValue);

            var pointsTypeProto = _protoMan.Index(key);

            var pointsLabel = new Label
            {
                Text = pointsTypeProto.LocalizedName,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                MinWidth = 120,
                MinHeight = 29,
                FontColorOverride = pointsTypeProto.Color
            };

            PointsLabels.AddChild(pointsLabel);

            var storageLabel = new Label
            {
                Text = value.ToString(),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                MinWidth = 120,
                MinHeight = 29,
                FontColorOverride = pointsTypeProto.Color
            };

            StoragePoints.AddChild(storageLabel);

            var diskLabel = new Label
            {
                Text = diskValue.ToString(),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                MinWidth = 120,
                MinHeight = 29,
                FontColorOverride = diskPointsExist ? pointsTypeProto.Color : NoPointsColor
            };

            DiskPoints.AddChild(diskLabel);

            var box = new SpinBox
            {
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Value = (int) _points.PointsDict[key],
                MinWidth = 120,
                IsValid = val => val is >= 0 and <= 1000000
            };
            box.ValueChanged += args => UpdatePointsValue(key, args.Value);

            PointsSpins.AddChild(box);
        }
    }

    private void UpdatePointsValue(ProtoId<ResearchPointsTypePrototype> type, double value)
    {
        if (_points.PointsDict.ContainsKey(type))
            _points.PointsDict[type] = value;
    }

    private void OnTransfer(BaseButton.ButtonEventArgs eventArgs)
    {
        TransferButtonPressed?.Invoke(_points, DirectionButton.Pressed);
    }

    private void OnMinimum(BaseButton.ButtonEventArgs eventArgs)
    {
        foreach (var children in PointsSpins.Children)
        {
            if (children is not SpinBox spin)
                continue;

            spin.Value = 0;
        }
    }

    private void OnMaximum(BaseButton.ButtonEventArgs eventArgs)
    {
        var maxDict = DirectionButton.Pressed ? _maxPointsStorage : _maxPointsDisk;

        var counter = -1;

        foreach (var (_, value) in maxDict.PointsDict)
        {
            counter += 1;

            if (PointsSpins.Children[counter] is not SpinBox spin)
                continue;

            spin.Value = value.Int();
        }
    }
}
