using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Client.RichText;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.RichText;
using Content.Shared.Construction.Components;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Materials;
using Content.Shared._WL.Research.Components;
using Content.Shared._WL.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class PointsDataReadMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    /*
    private readonly ItemSlotsSystem _itemSlots;
    private readonly FlatpackSystem _flatpack;
    private readonly MaterialStorageSystem _materialStorage;
    */

    private EntityUid _owner;

    private Dictionary<ProtoId<ResearchPointsTypePrototype>, double> _pointsDict = new();

    public static readonly EntProtoId NoBoardEffectId = "FlatpackerNoBoardEffect";

    private EntityUid? _currentBoard = EntityUid.Invalid;

    public event Action? PackButtonPressed;

    public PointsDataReadMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ButtonTransfer.StyleClasses.Add(StyleClass.ButtonOpenLeft);
        ButtonTransfer.StyleClasses.Add(StyleClass.Positive);

        /*
        _itemSlots = _entityManager.System<ItemSlotsSystem>();
        _flatpack = _entityManager.System<FlatpackSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();

        PackButton.OnPressed += _ => PackButtonPressed?.Invoke();

        InsertLabel.SetMarkup(Loc.GetString("flatpacker-ui-insert-board"));
        */
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
        //MaterialStorageControl.SetOwner(uid);
    }

    public void UpdatePoints(PointsDataReadBoundUserInterfaceState state)
    {
        StoragePoints.Children.Clear();
        PointsSpins.Children.Clear();
        DiskPoints.Children.Clear();
        _pointsDict.Clear();

        foreach (var (key, value) in state.StoragePointsData)
        {
            _pointsDict.Add(key, 0);

            var storageLabel = new Label
            {
                Text = value.ToString(),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                MinWidth = 120,
                MinHeight = 40
            };

            StoragePoints.AddChild(storageLabel);

            double diskValue = 0;

            if (state.DiskPointsData is not null &&
                state.DiskPointsData.TryGetValue(key, out var diskDictValue))
            {
                diskValue = diskDictValue;
            }

            var diskLabel = new Label
            {
                Text = diskValue.ToString(),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                MinWidth = 120,
                MinHeight = 40
            };

            DiskPoints.AddChild(diskLabel);

            var box = new SpinBox
            {
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Value = (int) _pointsDict[key],
                MinWidth = 120,
                IsValid = val => val is >= 0 and <= 1000000,
            };
            box.ValueChanged += args => UpdatePointsValue(key, args.Value);

            PointsSpins.AddChild(box);
        }
    }

    private void UpdatePointsValue(ProtoId<ResearchPointsTypePrototype> type, double value)
    {
        if (_pointsDict.ContainsKey(type))
            _pointsDict[type] = value;
    }
}
