using System.Linq;
using Content.Shared.Research.Prototypes;
using Content.Shared.Materials;
using Content.Shared.Materials.OreSilo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class RecipesMenuControl : ScrollContainer
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    private EntityUid? _owner;

    private List<ProtoId<LatheRecipePrototype>> _recipes;
    public List<ProtoId<LatheRecipePrototype>> ChoosedRecipes { get; private set; }

    public RecipesMenuControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _recipes = new();
        ChoosedRecipes = new();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void SetRecipes(int recipesCount)
    {
        recipesCount = Math.Min(RecipesList.Children.Count(), recipesCount);
        ChoosedRecipes.Clear();

        var count = -1;
        foreach (var control in RecipesList.Children.ToList().GetRange(0, recipesCount))
        {
            count += 1;

            if (control is not Button button)
                continue;

            ToggleChooseRecipe(button, _recipes[count]);
        }
    }

    public void UpdateRecipes(List<ProtoId<LatheRecipePrototype>> recipesRawList)
    {
        _recipes = recipesRawList;

        RecipesList.Children.Clear();
        foreach (var id in _recipes)
        {
            var mainButton = new Button {
                VerticalExpand = true,
                HorizontalExpand = true,
                Margin = new Thickness(4),
                Text = id
            };

            mainButton.OnPressed += args => ToggleChooseRecipe(args.Button, id);

            RecipesList.AddChild(mainButton);
        }
    }

    private void ToggleChooseRecipe(BaseButton button, ProtoId<LatheRecipePrototype> protoId)
    {
        if (ChoosedRecipes.Remove(protoId))
        {
            button.Pressed = false;
        }
        else
        {
            ChoosedRecipes.Add(protoId);
            button.Pressed = true;
        }
    }
}
