using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Client.RichText;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.RichText;
using Content.Shared.Construction.Components;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Materials;
using Content.Shared.Research.Prototypes;
using Content.Shared._WL.Research;
using Content.Shared._WL.Research.Components;
using Content.Shared._WL.Research.Prototypes;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class RecipesReaderMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    private EntityUid _owner;

    private List<ProtoId<LatheRecipePrototype>> _recipes = new();

    public static readonly EntProtoId NoBoardEffectId = "FlatpackerNoBoardEffect";

    public static readonly Color NoPointsColor = Color.FromHex("#222222");

    public event Action<ResearchPointsSpecifier, bool>? TransferButtonPressed;

    public RecipesReaderMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        /*
        ButtonTransfer.StyleClasses.Add(StyleClass.ButtonOpenLeft);
        ButtonTransfer.StyleClasses.Add(StyleClass.Positive);

        ButtonTransfer.OnPressed += OnTransfer;

        ButtonMinimum.OnPressed += OnMinimum;
        ButtonMaximum.OnPressed += OnMaximum;

        _itemSlots = _entityManager.System<ItemSlotsSystem>();
        _flatpack = _entityManager.System<FlatpackSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();

        InsertLabel.SetMarkup(Loc.GetString("flatpacker-ui-insert-board"));
        */
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;

        DataStorageCard.SetOwner(uid);
        StorageRecipesMenu.SetOwner(uid);
        DiskRecipesMenu.SetOwner(uid);
    }

    public void UpdateRecipes(RecipesReaderBoundUserInterfaceState state)
    {
        StorageRecipesMenu.UpdateRecipes(state.StorageRecipesData);
        DiskRecipesMenu.UpdateRecipes(state.DiskRecipesData);
    }

    /*
    private void UpdatePointsValue(ProtoId<ResearchPointsTypePrototype> type, double value)
    {
        if (_points.PointsDict.ContainsKey(type))
            _points.PointsDict[type] = value;
    }

    private void OnTransfer(BaseButton.ButtonEventArgs eventArgs)
    {
        TransferButtonPressed?.Invoke(_points, DirectionButton.Pressed);
    }

    private void OnMinimum(BaseButton.ButtonEventArgs eventArgs)
    {
        foreach (var children in PointsSpins.Children)
        {
            if (children is not SpinBox spin)
                continue;

            spin.Value = 0;
        }
    }

    private void OnMaximum(BaseButton.ButtonEventArgs eventArgs)
    {
        var maxDict = DirectionButton.Pressed ? _maxPointsStorage : _maxPointsDisk;

        var counter = -1;

        foreach (var (_, value) in maxDict.PointsDict)
        {
            counter += 1;

            if (PointsSpins.Children[counter] is not SpinBox spin)
                continue;

            spin.Value = value.Int();
        }
    }
    */
}
