using System.Linq;
using Content.Shared.Research.Prototypes;
using Content.Shared.Materials;
using Content.Shared.Materials.OreSilo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class RecipesMenuControl : ScrollContainer
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    // private readonly MaterialStorageSystem _materialStorage;

    private EntityUid? _owner;

    // private Dictionary<ProtoId<MaterialPrototype>, int> _currentMaterials = new();
    private List<ProtoId<LatheRecipePrototype>> _choosedRecipes = new();

    public RecipesMenuControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // _materialStorage = _entityManager.System<MaterialStorageSystem>();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void SetRecipes(int count)
    {
        count = Math.Min(RecipesList.Children.Count(), count);
        _choosedRecipes.Clear();

        foreach (var control in RecipesList.Children.ToList().GetRange(0, count))
        {
            /*
            if (control is not Button button)
                continue;

            button.OnPressed.Invoke();
            */
        }
    }

    public void UpdateRecipes(List<ProtoId<LatheRecipePrototype>> recipesRawList)
    {
        RecipesList.Children.Clear();
        foreach (var id in recipesRawList)
        {
            var mainButton = new Button {
                VerticalExpand = true,
                HorizontalExpand = true,
                Margin = new Thickness(4),
                Text = id
            };

            mainButton.OnPressed += args => ToogleChooseRecipe(args, id);

            RecipesList.AddChild(mainButton);
        }
    }

    private void ToogleChooseRecipe(BaseButton.ButtonEventArgs eventArgs, ProtoId<LatheRecipePrototype> protoId)
    {
        if (_choosedRecipes.Remove(protoId))
        {
            eventArgs.Button.Pressed = false;
        }
        else
        {
            _choosedRecipes.Add(protoId);
            eventArgs.Button.Pressed = true;
        }
    }
}
