using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.Access.Components;
using Content.Shared.Access.Systems;
using Content.Shared._WL.Research.Components;
using Content.Shared._WL.Research.Systems;
using Content.Shared._WL.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Timing;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchMainConsoleMenu : FancyWindow
{
    public Action<string>? OnResearchStartPressed;
    public Action? OnServerButtonPressed;

    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IGameTiming _timing = default!;
    private readonly SharedResearchNewSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    public EntityUid Entity;

    private Dictionary<ProtoId<ResearchPrototype>, ResearchState> _researches;

    public ResearchMainConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _research = _entity.System<SharedResearchNewSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        _researches = new();

        TabContainer.SetTabTitle(0, Loc.GetString("ui-main-terminal-tab-statistic"));
        TabContainer.SetTabTitle(1, Loc.GetString("ui-main-terminal-tab-tech"));

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        ResearchButton.OnPressed += _ => {
            if (TechTree.SelectedResearch is { } researchId)
                OnResearchStartPressed?.Invoke(researchId);
        };
        TechTree.OnTechnologyPressed += research => UpdateTechnologyBar(research);
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
    }

    public void UpdatePoints(ResearchMainConsoleBoundInterfaceState state)
    {
        PointsTypesContainer.Children.Clear();
        PointsValuesContainer.Children.Clear();

        var pointsData = state.PointsData;

        foreach (var (typeId, (curValue, maxValue, psValue)) in pointsData)
        {
            var typeProto = _protoMan.Index<ResearchPointsTypePrototype>(typeId);
            var typeLabel = new Label
            {
                Text = typeProto.LocalizedName,
                FontColorOverride = typeProto.Color,
                HorizontalAlignment = Label.HAlignment.Left
            };

            var typeContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                VerticalExpand = true,
                HorizontalExpand = true,
                Margin = new Thickness(4),
                SizeFlagsStretchRatio = 2,
                Children = { typeLabel }
            };

            PointsTypesContainer.AddChild(typeContainer);

            var valuesContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                VerticalExpand = true,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 2,
                Margin = new Thickness(10, 1, 0, 0)
            };

            var enumValues = new List<FixedPoint2>();

            enumValues.Add(curValue);
            enumValues.Add(maxValue);
            enumValues.Add(psValue);

            foreach (var value in enumValues)
            {
                var valueBox = new BoxContainer
                {

                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    VerticalExpand = true,
                    HorizontalExpand = true,
                    Margin = new Thickness(4),
                    MinWidth = 120,
                    Children = { new Label
                        {
                            Text = value.ToString(),
                            FontColorOverride = typeProto.Color,
                            HorizontalAlignment = Label.HAlignment.Center
                        }
                    }
                };

                valuesContainer.AddChild(valueBox);
            }

            PointsValuesContainer.AddChild(valuesContainer);
        }
    }

    public void UpdateResearches(ResearchMainConsoleBoundInterfaceState state)
    {
        _researches = state.ResearchesData;

        TabContainer.SetTabVisible(1, state.RootResearch is not null);

        ResearchQueueContainer.Children.Clear();
        ResearchQueueContainer.AddChild(new Control
        {
            MinHeight = 10
        });

        foreach (var resId in state.ResearchQueue)
        {
            var resProto = _protoMan.Index<ResearchPrototype>(resId);
            var resState = _researches[resId];
            var cardControl = new ResearchQueueCardControl(resProto, resState, _protoMan, _sprite, (float)_timing.CurTime.TotalMilliseconds/1000f);
            cardControl.OnPressed += () => OnResearchStartPressed?.Invoke(resId);
            ResearchQueueContainer.AddChild(cardControl);
        }

        if (state.RootResearch is { } research)
            TechTree.SetResearches(research, _researches);

        if (TechTree.SelectedResearch is { } selectedResearch)
        {
            UpdateTechnologyBar(selectedResearch);
            return;
        }
        else
        {
            UpdateTechnologyBar(null);
        }
    }

    private void UpdateTechnologyBar(string? researchId)
    {
        if (TechTree.SelectedResearch is not null)
            researchId ??= TechTree.SelectedResearch;

        researchId ??= string.Empty;

        if (!_protoMan.TryIndex<ResearchPrototype>(researchId, out var research))
            return;

        var state = _researches[researchId];

        ResearchTexture.Texture = _sprite.Frame0(research.Icon);
        ResearchTexture.TextureScale = new Vector2(2f);

        TechLabel.Text = Loc.GetString(research.Name);
        TechDesc.SetMessage(_research.GetResearchDescription(researchId));

        ResearchBar.Value = state.ResearchedPackages.Float() / research.PackagesCost.Float() * 100f;
        ProgressLabel.Text = Loc.GetString("research-progress-label",
                ("value", state.ResearchedPackages),
                ("maxValue", research.PackagesCost)
            );
    }

    /*
    /// <summary>
    ///     Synchronize a container for technology cards with a list of technologies,
    ///     creating or removing UI cards as appropriate.
    /// </summary>
    /// <param name="container">The container which contains the UI cards</param>
    /// <param name="technologies">The current set of technologies for which there should be cards</param>
    private void SyncTechnologyList(BoxContainer container, IEnumerable<TechnologyPrototype> technologies)
    {
        // For the cards which already exist, build a map from technology prototype to the UI card
        var currentTechControls = new Dictionary<TechnologyPrototype, Control>();
        foreach (var child in container.Children)
        {
            if (child is MiniTechnologyCardControl)
            {
                currentTechControls.Add((child as MiniTechnologyCardControl)!.Technology, child);
            }
        }

        foreach (var tech in technologies)
        {
            if (!currentTechControls.ContainsKey(tech))
            {
                // Create a card for any technology which doesn't already have one.
                var mini = new MiniTechnologyCardControl(tech, _protoMan, _sprite, _research.GetTechnologyDescription(tech));
                container.AddChild(mini);
            }
            else
            {
                // The tech already exists in the UI; remove it from the set, so we won't revisit it below
                currentTechControls.Remove(tech);
            }
        }

        // Now, any items left in the dictionary are technologies which were previously
        // available, but now are not. Remove them.
        foreach (var (tech, techControl) in currentTechControls)
        {
            container.Children.Remove(techControl);
        }
    }
    */
}
