using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared._WL.Research.Components;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchScannerMenu : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;

    public FormattedMessage Output = new();
    public TimeSpan? NextPulseTime;

    public ResearchScannerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateOutput(ResearchScannerUserInterfaceState state)
    {
        if (state.ClearOutput)
        {
            Output = state.Message;
        }
        else
        {
            Output.PushNewline();
            Output.AddMarkupOrThrow(state.Message.ToString());
        }

        ScannerText.SetMarkup(Output.ToMarkup());
    }

    /*
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (NextPulseTime != null)
            UpdateMenu();
    }
    */
}
