using Content.Shared.Research.Prototypes;
using Content.Shared._WL.Research.Prototypes;
using Content.Shared._WL.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchQueueCardControl : Control
{
    public Action? OnPressed;

    public ResearchQueueCardControl(ResearchPrototype researchProto, ResearchState researchState, IPrototypeManager prototypeManager, SpriteSystem spriteSys, float time)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index<TechDisciplinePrototype>(researchProto.Discipline);
        //Background.PanelOverride.BorderColor = discipline.Color;

        ResearchName.Text = researchProto.LocalizedName;
        ResearchIcon.Texture = spriteSys.Frame0(researchProto.Icon);

        /*
        if (true)
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");
        */

        MainBar.MinValue = 0f;
        MainBar.MaxValue = (float)researchState.PackagesCostModed;
        MainBar.Value = (float)researchState.ResearchedPackages;
        MainBar.SetTime(time);

        ResearchProgress.Text = $"{MainBar.Value}/{MainBar.MaxValue}";

        switch (researchState.Status)
        {
            case ResearchStatus.NotResearched:
                break;
        }

        //ResearchButton.Disabled = points < technology.Cost || !hasAccess;
        ResearchButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
