using System.Numerics;
using Content.Shared.Research.Prototypes;
using Content.Shared._WL.Research.Prototypes;
using Content.Shared._WL.Research.Components;
using Content.Shared.Containers.ItemSlots;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Timing;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchHintControl : Control
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    private readonly SpriteSystem _sprite;

    private ProtoId<ResearchPrototype>? _protoId;

    private ResearchState? _state;

    public static readonly EntProtoId NoDiskEffectId = "DataReaderNoDiskEffect";

    public ResearchHintControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();
    }

    public void SetResearch(ProtoId<ResearchPrototype> protoId, ResearchState state)
    {
        _protoId = protoId;
        _state = state;
        UpdateHint();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateHint();
    }

    private void UpdateHint()
    {
        if (!_protoMan.TryIndex<ResearchPrototype>(_protoId, out var proto))
            return;

        IconTexture.Texture = _sprite.Frame0(proto.Icon);
        IconTexture.TextureScale = new Vector2(2f);;
        ResearchName.Text = Loc.GetString(proto.Name);
    }
}
