using System.Numerics;
using Content.Shared.Research.Prototypes;
using Content.Shared._WL.Research.Prototypes;
using Content.Shared._WL.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyTreeControl : LayoutContainer
{
    public Action<string>? OnTechnologyPressed;

    private bool Draggable { get; } = true;
    private float WorldMinRange;
    private float WorldMaxRange;
    private float WorldRange;

    private ProtoId<ResearchPrototype>? _rootResearch;
    private Dictionary<ProtoId<ResearchPrototype>, ResearchState> _researches;

    private ProtoId<ResearchPrototype>? _hoveredResearch;
    public ProtoId<ResearchPrototype>? SelectedResearch;

    private const float LayerRadius = 10f;

    public const int UIDisplayRadius = 320;
    private const int MinimapMargin = 4;

    private int MidPoint => SizeFull / 2;
    private int SizeFull => (int) ((UIDisplayRadius + MinimapMargin) * 2 * UIScale);
    private Vector2 MidPointVector => new Vector2(MidPoint, MidPoint);
    private int ScaledMinimapRadius => (int) (UIDisplayRadius * UIScale);
    private float MinimapScale => WorldRange != 0 ? ScaledMinimapRadius / WorldRange : 0f;
    private float NodeRadius => 3 * UIScale;

    private readonly Font _font;

    private bool _draggin;
    private float range = 32f;

    public Vector2 Offset;

    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IGameTiming _timing = default!;
    private readonly SpriteSystem _sprite;

    public TechnologyTreeControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();

        var fontResource = IoCManager.Resolve<IResourceCache>()
            .GetResource<FontResource>("/EngineFonts/NotoSans/NotoSansMono-Regular.ttf");
        _font = new VectorFont(fontResource, 16);


        // SetSize = new Vector2(SizeFull, SizeFull);
        MouseFilter = MouseFilterMode.Stop;
        WorldMinRange = 1f;
        WorldMaxRange = 32f;
        RectClipContent = true;

        _rootResearch = null;
        _researches = new();
    }

    public void SetResearches(ProtoId<ResearchPrototype> rootResearch, Dictionary<ProtoId<ResearchPrototype>, ResearchState> researches)
    {
        _rootResearch = rootResearch;
        _researches = researches;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        _hoveredResearch = null;

        var offsetVec = new Vector2(Offset.X, -Offset.Y);

        var positionTopLeft = ScalePosition(new Vector2(-10, -10) - offsetVec);
        var positionBottomRight = ScalePosition(new Vector2(10, 10) - offsetVec);

        var box = new UIBox2(positionTopLeft, positionBottomRight);
        // handle.DrawRect(box, Color.White);

        if (_rootResearch is not null)
            RecursyDrawPoints(handle, _rootResearch.Value, 0f, MathHelper.TwoPi, 0, 1, offsetVec);

        if (_hoveredResearch is { } hovered)
        {
            var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
            DrawNodeHint(handle, cursor, hovered);
        }
        else
        {
            ResearchHint.Visible = false;
        }

        if (!range.Equals(WorldRange))
        {
            var diff = range - WorldRange;
            const float lerpRate = 10f;

            WorldRange += (float) Math.Clamp(diff, -lerpRate * MathF.Abs(diff) * _timing.FrameTime.TotalSeconds, lerpRate * MathF.Abs(diff) * _timing.FrameTime.TotalSeconds);
        }
    }

    private Vector2 RecursyDrawPoints(DrawingHandleScreen handle, ProtoId<ResearchPrototype> protoId, float startAngle, float sectorAngle, float count, float maxCount, Vector2 offsetVec, int layer = 0)
    {
        var proto = _protoMan.Index(protoId);
        var state = _researches[protoId];

        var angle = sectorAngle * count / maxCount + startAngle + sectorAngle / maxCount / 2;
        var offset = RadialToVector(layer * LayerRadius, angle);
        var pos = ScalePosition(offset - offsetVec);
        var scaledRadius = NodeRadius * MinimapScale;

        DrawCircle(handle, pos, scaledRadius, Color.White, filled: false);

        var childSectorAngle = sectorAngle / maxCount;

        var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;

        if (SelectedResearch == protoId)
        {
            DrawCircle(handle, pos, scaledRadius, Color.Gray);
        }

        var hovered = (cursor - pos).LengthSquared() <= scaledRadius * scaledRadius;
        if (hovered)
        {
            _hoveredResearch = protoId;
            DrawCircle(handle, pos, scaledRadius, Color.White);
        }

        var texture = _sprite.Frame0(proto.Icon);
        var size = scaledRadius / 1.4f * 2;
        handle.DrawTextureRect(texture, UIBox2.FromDimensions(pos - new Vector2(size / 2), new Vector2(size)));

        /*
        var dimensions = handle.GetDimensions(_font, proto.LocalizedName, 1);
        handle.DrawString(_font, pos - new Vector2(dimensions.X / 2, dimensions.Y / 2), proto.LocalizedName, Color.White);
        */

        var childCount = 0;
        foreach (var child in proto.ChildrenResearches)
        {
            var childPos = RecursyDrawPoints(
                    handle,
                    child,
                    angle - childSectorAngle / 2, childSectorAngle,
                    childCount,
                    proto.ChildrenResearches.Count,
                    offsetVec,
                    layer + 1
            );
            var lineVec = Vector2.Normalize(childPos - pos) * scaledRadius;
            handle.DrawLine(pos + lineVec, childPos - lineVec, Color.White);
            childCount += 1;
        }

        return pos;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);
        AddControlRange(-args.Delta.Y * 1f / 8f * range);
    }

    public void AddControlRange(float value)
    {
        range = Math.Clamp(range + value, WorldMinRange, WorldMaxRange);
    }

    private Vector2 ScalePosition(Vector2 value)
    {
        return ScalePosition(value, MinimapScale, MidPointVector);
    }

    private static Vector2 ScalePosition(Vector2 value, float minimapScale, Vector2 midpointVector)
    {
        return value * minimapScale + midpointVector;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        Offset -= new Vector2(args.Relative.X, -args.Relative.Y) / MidPoint * WorldRange;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (!Draggable)
            return;

        if (args.Function == EngineKeyFunctions.Use)
        {
            // StartDragPosition = args.PointerLocation.Position;
            _draggin = true;
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (!Draggable)
            return;

        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        if (_hoveredResearch == null)
            return;

        SelectedResearch = _hoveredResearch;

        OnTechnologyPressed?.Invoke(SelectedResearch.Value);
        UserInterfaceManager.ClickSound();
    }

    private Vector2 RadialToVector(float radius, float angle)
    {
        return new Vector2((float)Math.Cos(angle), (float)Math.Sin(angle)) * radius;
    }

    private void DrawCircle(DrawingHandleScreen handle, Vector2 position, float radius, Color color, float start = 0f, float end = MathHelper.TwoPi, bool filled = true)
    {
        const int segments = 256;
        var buffer = new Span<Vector2>(new Vector2[segments + 1]);

        for (var i = 0; i <= segments; i++)
        {
            var angle = start + i / (float) segments * (end - start);
            var pos = new Vector2(MathF.Sin(angle), MathF.Cos(angle));

            buffer[i] = position + pos * radius;
        }

        DrawPrimitiveTopology type = filled ? DrawPrimitiveTopology.TriangleFan : DrawPrimitiveTopology.LineStrip;
        handle.DrawPrimitives(type, buffer, color);
    }

    private void DrawNodeHint(DrawingHandleScreen handle, Vector2 position, ProtoId<ResearchPrototype> protoId)
    {
        var size = new Vector2(1.2f, 0.5f) * ScaledMinimapRadius;

        var box = UIBox2.FromDimensions(position, size);

        ResearchHint.SetResearch(protoId, _researches[protoId]);
        ResearchHint.Visible = true;
        ResearchHint.Arrange(box);
        ResearchHint.SetSize = size;
    }
}
