using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.Access.Components;
using Content.Shared.Access.Systems;
using Content.Shared._WL.Research.Components;
using Content.Shared._WL.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Timing;

namespace Content.Client._WL.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class UniversalComputerMenu : FancyWindow
{
    public Action<string>? OnProgramOpenPressed;

    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    public UniversalComputerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdatePrograms(UniversalComputerBoundInterfaceState state)
    {
        if (Disposed)
            return;

        ProgramsMenu.Children.Clear();

        foreach (var protoId in state.Programs)
        {
            var program = _protoMan.Index(protoId);

            var programBox = new Button {
                VerticalExpand = true,
                HorizontalExpand = true,
                Margin = new Thickness(4),
                Text = program.LocalizedName
            };

            programBox.OnPressed += args => OnProgramOpenPressed?.Invoke(protoId);

            ProgramsMenu.AddChild(programBox);
        }
    }
}
