using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CorvaxGoob.ImageVisuals.UI;

[GenerateTypedNameReferences]
public sealed partial class ImageVisualsWindow : BaseWindow
{
    private const int DRAG_MARGIN_SIZE = 16;

    public ImageVisualsWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
    }
    public void SetImage(ResPath imagePath, Vector2 imageSize)
    {
        ImageDisplay.TexturePath = imagePath.ToString();
        SetSize = imageSize;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.None;

        if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
        {
            mode |= DragMode.Top;
        }
        else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
        {
            mode |= DragMode.Bottom;
        }

        if (relativeMousePos.X < DRAG_MARGIN_SIZE)
        {
            mode |= DragMode.Left;
        }
        else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
        {
            mode |= DragMode.Right;
        }
        if (mode == DragMode.None)
        {
            return DragMode.Move;
        }

        return mode;
    }
}
