using System.Numerics;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._WL.CharacterInformation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WL.CharacterInformation;

[GenerateTypedNameReferences]
public sealed partial class CharacterInformationWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private float _accumulatedTime;

    public CharacterInformationWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("character-information-ui-sprite"));
        Tabs.SetTabTitle(1, Loc.GetString("character-information-ui-flavor-text"));
        Tabs.SetTabTitle(2, Loc.GetString("character-information-ui-ooc-text"));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _accumulatedTime += args.DeltaSeconds;
        CharSprite.OverrideDirection = (Direction) ((int) _accumulatedTime % 4 * 2);
    }

    public void UpdateState(CharacterInformationBuiState state)
    {
        CharSprite.SetEntity(_entity.GetEntity(state.Uid));
        Name.SetMarkup($"[bold]{state.CharacterName}[/bold]");

        if (!string.IsNullOrEmpty(state.FlavorText))
        {
            FlavorText.SetMessage(state.FlavorText);
            FlavorTextLabel.Text = Loc.GetString("character-information-ui-flavor-text") + ":";
        }
        else
        {
            FlavorText.SetMessage("");
            FlavorTextLabel.Text = Loc.GetString("character-information-ui-no-flavor-text");
        }

        if (!string.IsNullOrEmpty(state.OocText))
        {
            OocText.SetMessage(state.OocText);
            OocTextLabel.Text = Loc.GetString("character-information-ui-ooc-text") + ":";
        }
        else
        {
            OocText.SetMessage("");
            OocTextLabel.Text = Loc.GetString("character-information-ui-no-ooc-text");
        }

        SetWidth = Size.X + 0.1f;
    }
}
