using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._WL.CharacterInformation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WL.CharacterInformation;

[GenerateTypedNameReferences]
public sealed partial class CharacterInformationWindow : FancyWindow
{
    private float _accumulatedTime;

    public CharacterInformationWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _accumulatedTime += args.DeltaSeconds;
        CharSprite.OverrideDirection = (Direction) ((int) _accumulatedTime % 4 * 2);
    }

    public void UpdateState(CharacterInformationBuiState state)
    {
        CharSprite.SetEntity(state.Uid);
        Name.SetMessage(FormattedMessage.FromMarkup($"[bold]{state.CharacterName}[/bold]"));

        if (!string.IsNullOrEmpty(state.FlavorText))
        {
            FlavorText.SetMessage(state.FlavorText);
            FlavorTextLabel.Visible = true;
        }
        if (!string.IsNullOrEmpty(state.OocText))
        {
            OocText.SetMessage(state.OocText);
            OocTextLabel.Visible = true;
        }

        if (string.IsNullOrEmpty(state.FlavorText) && string.IsNullOrEmpty(state.OocText))
        {
            Separator.Visible = false;
            TextScroll.Visible = false;
            RootWindow.MinSize = new Vector2(280, 350);
            RootWindow.SetSize = new Vector2(280, 350);
        }
        else
        {
            RootWindow.MinSize = new Vector2(700, 350);
            RootWindow.SetSize = new Vector2(700, 350);
        }
    }
}
