using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.SafeCode;

[GenerateTypedNameReferences]
public sealed partial class SafeCodeWindow : FancyWindow
{
    private string _input = string.Empty;
    private int _maxLength = 0;
    public event Action<string>? OnSubmit;
    public event Action? OnLock;
    private bool _locked = true;

    public SafeCodeWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);


        ZeroButton.OnPressed += _ => AddNumber("0");
        OneButton.OnPressed += _ => AddNumber("1");
        TwoButton.OnPressed += _ => AddNumber("2");
        ThreeButton.OnPressed += _ => AddNumber("3");
        FourButton.OnPressed += _ => AddNumber("4");
        FiveButton.OnPressed += _ => AddNumber("5");
        SixButton.OnPressed += _ => AddNumber("6");
        SevenButton.OnPressed += _ => AddNumber("7");
        EightButton.OnPressed += _ => AddNumber("8");
        NineButton.OnPressed += _ => AddNumber("9");


        ClearButton.OnPressed += _ =>
        {
            _input = string.Empty;
            UpdateDisplay();
        };


        SubmitButton.OnPressed += _ =>
        {
            SubmitButton.Disabled = _input.Length != _maxLength;

            OnSubmit?.Invoke(_input);
        };

        LockButton.OnPressed += _ => OnLock?.Invoke();

        UpdateDisplay();
    }

    private void AddNumber(string number)
    {
        if (_input.Length >= _maxLength)
            return;

        _input += number;

        UpdateDisplay();
    }
    private bool CanSubmit()
    {
        return _locked && _input.Length == _maxLength;
    }

    private void UpdateDisplay()
    {
        CodeDisplay.Text = _input.PadRight(_maxLength, '_');

        SubmitButton.Disabled = !CanSubmit();
    }

    public void UpdateState(int maxLength, bool locked, bool? lastAttemptCorrect)
    {
        _maxLength = maxLength;
        _locked = locked;

        if (lastAttemptCorrect == false)
            _input = string.Empty;

        ErrorLabel.Visible = lastAttemptCorrect == false;
        LockButton.Visible = !locked;

        UpdateDisplay();
    }
}
