using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.Languages.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguagesSelectSimple : Control
{
    public event Action? OnTraitToggle;

    private static readonly Color ColorDefault = Color.FromHex("#25252A");
    private static readonly Color ColorError = Color.FromHex("#3F2A2A");

    public LanguagesSelectSimple()
    {
        RobustXamlLoader.Load(this);
        ToggleButton.OnPressed += _ => OnTraitToggle?.Invoke();
    }

    public void SetLanguage(string name, string description, int cost)
    {
        NameLabel.Text = name;
        DescriptionLabel.Text = description;

        if (cost > 0)
            CostLabel.Text = Loc.GetString("ui-languages-cost", ("cost", cost));
        else if (cost < 0)
            CostLabel.Text = Loc.GetString("ui-languages-bonus", ("bonus", Math.Abs(cost)));
        else
            CostLabel.Text = Loc.GetString("ui-languages-free");
    }

    public void SetActive(bool active)
    {
        ToggleButton.Pressed = active;
    }

    public void PlayErrorAnimation()
    {
    }
}
