using Content.Shared._WL.Languages;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.Timing;

namespace Content.Client._WL.Languages.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguagesSelect : Control
{
    [Dependency] private IEntitySystemManager _entitySystemManager = default!;

    public event Action<int>? OnTraitToggle;

    private int? _selectedLevel;
    private LanguagePrototype? _languagePrototype;
    private string _speciesId = string.Empty;
    private string _confederationId = string.Empty;
    private int _legacyBaseCost;

    private static readonly Color ColorSelected = Color.FromHex("#2A3F2A");
    private static readonly Color ColorDefault = Color.FromHex("#25252A");
    private static readonly Color ColorError = Color.FromHex("#3F2A2A");

    public LanguagesSelect()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Level1Button.OnPressed += _ => OnTraitToggle?.Invoke(1);
        Level2Button.OnPressed += _ => OnTraitToggle?.Invoke(2);
        Level3Button.OnPressed += _ => OnTraitToggle?.Invoke(3);
        Level4Button.OnPressed += _ => OnTraitToggle?.Invoke(4);
    }

    public void SetLanguage(
        string name,
        string description,
        LanguagePrototype languagePrototype,
        string speciesId,
        string confederationId,
        int legacyBaseCost = 0)
    {
        _languagePrototype = languagePrototype;
        _speciesId = speciesId;
        _confederationId = confederationId;
        _legacyBaseCost = legacyBaseCost;

        NameLabel.Text = name;
        DescriptionLabel.Text = description;

        LoadLanguageIcon();
        UpdateButtonAvailability();
        UpdateButtonLabels();
        UpdateAppearance();
        UpdateCostLabel();
        UpdateColorPanel();
    }

    private void LoadLanguageIcon()
    {
        LanguageIcon.Texture = null;
        if (_languagePrototype?.Icon == null)
            return;

        var spriteSystem = _entitySystemManager.GetEntitySystem<SpriteSystem>();
        LanguageIcon.Texture = spriteSystem.Frame0(_languagePrototype.Icon);
    }

    public void SetSelectedLevel(int? level)
    {
        _selectedLevel = level;
        UpdateAppearance();
        UpdateCostLabel();
        UpdateColorPanel();
    }

    private void UpdateButtonAvailability()
    {
        if (_languagePrototype == null)
        {
            Level1Button.Disabled = false;
            Level2Button.Disabled = false;
            Level3Button.Disabled = false;
            Level4Button.Disabled = false;
            return;
        }

        Level1Button.Disabled = !IsLevelAvailable(1);
        Level2Button.Disabled = !IsLevelAvailable(2);
        Level3Button.Disabled = !IsLevelAvailable(3);
        Level4Button.Disabled = !IsLevelAvailable(4);
    }

    private bool IsLevelAvailable(int level)
    {
        if (_languagePrototype == null)
            return true;

        if (!LanguageCostSystem.IsLevelConfigured(_languagePrototype, level))
            return false;

        return LanguageCostSystem.TryGetTotalCostForLevel(
            _languagePrototype,
            level,
            _speciesId,
            _confederationId,
            out _);
    }

    private void UpdateButtonLabels()
    {
        UpdateButtonLabel(Level1Button, "languages-level-1", 1);
        UpdateButtonLabel(Level2Button, "languages-level-2", 2);
        UpdateButtonLabel(Level3Button, "languages-level-3", 3);
        UpdateButtonLabel(Level4Button, "languages-level-4", 4);
    }

    private void UpdateButtonLabel(Button button, string locKey, int level)
    {
        var baseText = Loc.GetString(locKey);
        var costText = GetCostTextForLevel(level);

        if (costText == Loc.GetString("ui-languages-locked"))
            button.Text = $"{baseText} {costText}";
        else
            button.Text = $"{baseText} ({costText})";
    }

    private string GetCostTextForLevel(int level)
    {
        if (_languagePrototype == null || _languagePrototype.LevelCosts.Count == 0)
        {
            var fallbackCost = _legacyBaseCost * level;
            return FormatCost(fallbackCost);
        }

        if (!LanguageCostSystem.TryGetTotalCostForLevel(
                _languagePrototype,
                level,
                _speciesId,
                _confederationId,
                out var totalCost))
        {
            return Loc.GetString("ui-languages-locked");
        }

        return FormatCost(totalCost);
    }

    private string FormatCost(int cost)
    {
        if (cost <= 0)
            return Loc.GetString("ui-languages-free");
        return cost.ToString();
    }

    private void UpdateCostLabel()
    {
        var targetLevel = _selectedLevel ?? 1;

        if (_languagePrototype == null || _languagePrototype.LevelCosts.Count == 0)
        {
            var fallbackCost = _legacyBaseCost * targetLevel;
            CostLabel.Text = fallbackCost > 0
                ? Loc.GetString("ui-languages-cost", ("cost", fallbackCost))
                : Loc.GetString("ui-languages-free");
            CostLabel.FontColorOverride = null;
            return;
        }

        if (!LanguageCostSystem.TryGetTotalCostForLevel(
                _languagePrototype,
                targetLevel,
                _speciesId,
                _confederationId,
                out var totalCost))
        {
            CostLabel.Text = Loc.GetString("ui-languages-unavailable");
            CostLabel.FontColorOverride = Color.Red;
            return;
        }

        CostLabel.FontColorOverride = null;
        CostLabel.Text = totalCost > 0
            ? Loc.GetString("ui-languages-cost", ("cost", totalCost))
            : Loc.GetString("ui-languages-free");
    }

    private void UpdateAppearance()
    {
        Level1Button.Modulate = _selectedLevel >= 1 ? Color.Green : Color.White;
        Level2Button.Modulate = _selectedLevel >= 2 ? Color.Green : Color.White;
        Level3Button.Modulate = _selectedLevel >= 3 ? Color.Green : Color.White;
        Level4Button.Modulate = _selectedLevel >= 4 ? Color.Green : Color.White;
    }

    private void UpdateColorPanel()
    {
        var bgColor = _selectedLevel.HasValue ? ColorSelected : ColorDefault;
        ColorPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = bgColor,
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8,
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
        };
    }

    public void PlayErrorAnimation()
    {
        Level1Button.Modulate = Color.Red;
        Level2Button.Modulate = Color.Red;
        Level3Button.Modulate = Color.Red;
        Level4Button.Modulate = Color.Red;

        ColorPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = ColorError,
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8,
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
        };

        Timer.Spawn(TimeSpan.FromMilliseconds(300), () =>
        {
            UpdateAppearance();
            UpdateColorPanel();
        });
    }
}
