using System.Linq;
using Content.Shared._WL.Languages;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Content.Shared._WL.Languages.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WL.Languages.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguagesTab : Control
{
    private IPrototypeManager? _prototypeManager;
    private HumanoidCharacterProfile? _profile;

    public event Action<HumanoidCharacterProfile>? ProfileChanged;

    public LanguagesTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void Initialize(HumanoidCharacterProfile profile, IPrototypeManager prototypeManager)
    {
        _prototypeManager = prototypeManager;
        UpdateProfile(profile);
    }

    public void UpdateProfile(HumanoidCharacterProfile profile)
    {
        _profile = profile;
        RefreshLanguages();
    }

    private void RefreshLanguages()
    {
        if (_profile == null || _prototypeManager == null)
            return;

        LanguagesContainer.RemoveAllChildren();

        var languageTraits = _prototypeManager
            .EnumeratePrototypes<TraitPrototype>()
            .Where(t => t.Category?.Id == "Languages")
            .OrderBy(t => Loc.GetString(t.Name))
            .ToList();

        if (!languageTraits.Any())
        {
            LanguagesContainer.AddChild(new Label
            {
                Text = Loc.GetString("humanoid-profile-editor-no-traits"),
                FontColorOverride = Color.Gray,
            });
            return;
        }

        UpdatePointsLabel(languageTraits);

        foreach (var trait in languageTraits)
        {
            if (!LanguageCostSystem.TryGetLanguagePrototype(trait, _prototypeManager, out var languagePrototype))
            {
                CreateSimpleTraitControl(trait);
                continue;
            }

            var control = new LanguagesSelect();
            control.SetLanguage(
                Loc.GetString(trait.Name),
                Loc.GetString(trait.Description ?? "unknown"),
                languagePrototype,
                _profile.Species.Id,
                _profile.Confederation,
                trait.Cost);

            int? selectedLevel = null;
            if (_profile.LanguageLevels.TryGetValue(trait.ID, out var savedLevel))
                selectedLevel = savedLevel;

            control.SetSelectedLevel(selectedLevel);

            control.OnTraitToggle += clickedLevel =>
            {
                if (_profile == null || _prototypeManager == null)
                    return;

                var hasTrait = _profile.TraitPreferences.Contains(trait.ID);
                var activeLevel = _profile.LanguageLevels.GetValueOrDefault(trait.ID, 0);

                if (!LanguageCostSystem.TryGetTotalCostForLevel(
                        languagePrototype,
                        clickedLevel,
                        _profile.Species.Id,
                        _profile.Confederation,
                        out _))
                {
                    if (languagePrototype.LevelCosts.Count > 0)
                    {
                        control.PlayErrorAnimation();
                        return;
                    }
                }

                HumanoidCharacterProfile newProfile;

                if (hasTrait && activeLevel == clickedLevel)
                {
                    newProfile = _profile.WithoutLanguageLevel(trait.ID);
                    newProfile = newProfile.WithoutTraitPreference(trait.ID);
                }
                else if (hasTrait)
                {
                    newProfile = _profile.WithLanguageLevel(trait.ID, clickedLevel, _prototypeManager);

                    if (newProfile.LanguageLevels.GetValueOrDefault(trait.ID, 0) != clickedLevel)
                    {
                        control.PlayErrorAnimation();
                        return;
                    }
                }
                else
                {
                    newProfile = _profile.WithTraitPreference(trait.ID, _prototypeManager, clickedLevel);

                    if (!newProfile.TraitPreferences.Contains(trait.ID))
                    {
                        control.PlayErrorAnimation();
                        return;
                    }

                    newProfile = newProfile.WithLanguageLevel(trait.ID, clickedLevel);
                }

                _profile = newProfile;
                ProfileChanged?.Invoke(_profile);
                RefreshLanguages();
            };

            LanguagesContainer.AddChild(control);
        }
    }

    private void CreateSimpleTraitControl(TraitPrototype trait)
    {
        if (_profile == null)
            return;

        var isSpecieRemover = trait.Components.Values
            .Any(entry => entry.Component is ModifyLanguagesComponent { SpecieLanguage: true });

        if (!isSpecieRemover)
            return;

        var control = new LanguagesSelectSimple();
        control.SetLanguage(
            Loc.GetString(trait.Name),
            Loc.GetString(trait.Description ?? "unknown"),
            trait.Cost);
        control.SetActive(_profile.TraitPreferences.Contains(trait.ID));

        control.OnTraitToggle += () =>
        {
            if (_profile == null || _prototypeManager == null)
                return;

            HumanoidCharacterProfile newProfile;

            if (_profile.TraitPreferences.Contains(trait.ID))
            {
                newProfile = _profile.WithoutTraitPreference(trait.ID);
            }
            else
            {
                newProfile = _profile.WithTraitPreference(trait.ID, _prototypeManager);
                if (!newProfile.TraitPreferences.Contains(trait.ID))
                {
                    control.PlayErrorAnimation();
                    return;
                }
            }

            _profile = newProfile;
            ProfileChanged?.Invoke(_profile);
            RefreshLanguages();
        };

        LanguagesContainer.AddChild(control);
    }

    private void UpdatePointsLabel(List<TraitPrototype> languageTraits)
    {
        if (_profile == null || _prototypeManager == null)
            return;

        const string categoryId = "Languages";
        if (!_prototypeManager.TryIndex<TraitCategoryPrototype>(categoryId, out var category))
            return;

        if (category.MaxTraitPoints < 0)
        {
            var langCount = _profile.TraitPreferences.Count(t => languageTraits.Any(lt => lt.ID == t));
            PointsLabel.Text = Loc.GetString("languages-point-unlimited", ("count", langCount));
            PointsLabel.FontColorOverride = Color.White;
            return;
        }

        var spentPoints = 0;

        foreach (var trait in languageTraits)
        {
            if (!_profile.TraitPreferences.Contains(trait.ID))
                continue;

            var isSpecieRemover = trait.Components.Values
                .Any(entry => entry.Component is ModifyLanguagesComponent { SpecieLanguage: true });

            if (isSpecieRemover)
            {
                spentPoints += trait.Cost;
                continue;
            }

            var traitLevel = _profile.LanguageLevels.GetValueOrDefault(trait.ID, 1);

            if (LanguageCostSystem.TryGetLanguagePrototype(trait, _prototypeManager, out var languagePrototype) &&
                LanguageCostSystem.TryGetTotalCostForLevel(
                    languagePrototype,
                    traitLevel,
                    _profile.Species.Id,
                    _profile.Confederation,
                    out var languageCost))
            {
                spentPoints += languageCost;
            }
            else
            {
                spentPoints += trait.Cost * traitLevel;
            }
        }

        var remaining = category.MaxTraitPoints - spentPoints;
        PointsLabel.FontColorOverride = remaining >= 0 ? Color.White : Color.Red;

        PointsLabel.Text = Loc.GetString("languages-point",
            ("spent", spentPoints),
            ("max", category.MaxTraitPoints),
            ("remaining", remaining));
    }
}
