using Content.Client._WL.Records; // WL-Changes-Records
using Content.Shared._WL.Languages;
using Content.Shared._WL.Records; // WL-Records
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralRecord : Control
{
    public Action<uint>? OnDeletePressed;
    public GeneralRecord(GeneralStationRecord record, bool canDelete, uint? id, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        // WL-Changes-Records-Start
        // RecordName.Text = record.Name;
        // Age.Text = Loc.GetString("general-station-record-console-record-age", ("age", record.Age.ToString()));
        // Title.Text = Loc.GetString("general-station-record-console-record-title",
        //     ("job", record.JobTitle));
        // var species = Loc.GetString(prototypeManager.Index<SpeciesPrototype>(record.Species).Name);
        // Species.Text = Loc.GetString("general-station-record-console-record-species", ("species", species));
        // Gender.Text = Loc.GetString("general-station-record-console-record-gender",
        //     ("gender", record.Gender.ToString()));

        var identity = RecordIdentityBuilder.FromStationRecord(record, prototypeManager, Loc.GetString);
        RecordView.SetData(RecordViewBuilder.Employment(identity, record.EmploymentRecord, Loc.GetString, true));
        // WL-Changes-Records-End

        if (canDelete && id != null)
        {
            DeleteButton.Visible = true;
            DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke(id.Value);
        }
    }
}
