using System.Text.Json.Serialization;

namespace Content.Server._WL.ChatGpt.Elements.Response
{
    /// <summary>
    /// Класс характеризующий информацию о входящих и исходящих токенах.
    /// </summary>
    public sealed class GptTokenUsage
    {
        /// <summary>
        /// Количество токенов в промте.
        /// </summary>
        [JsonPropertyName("prompt_tokens")]
        public required int InputTokens { get; set; }

        /// <summary>
        /// Количество токенов в ответе модели.
        /// </summary>
        [JsonPropertyName("completion_tokens")]
        public required int OutputTokens { get; set; }

        /// <summary>
        /// Общее количество токенов.
        /// Сумма <see cref="InputTokens"/> и <see cref="OutputTokens"/>.
        /// </summary>
        [JsonPropertyName("total_tokens")]
        public required int TotalTokens { get; set; }

        /// <summary>
        /// Breakdown of tokens used in a completion.
        /// </summary>
        [JsonPropertyName("completion_tokens_details")]
        public CompletionTokensDetail? CompletionDetail { get; set; } = null;

        /// <summary>
        ///
        /// </summary>
        [JsonPropertyName("prompt_tokens_details")]
        public PromptTokensDetail? PromptDetail { get; set; } = null;

        /// <summary>
        /// Класс, использующийся для подробного описания количества токенов в ответе модели.
        /// </summary>
        public sealed class CompletionTokensDetail
        {
            /// <summary>
            /// Audio input tokens generated by the model.
            /// </summary>
            [JsonPropertyName("audio_tokens")]
            public int? AudioTokens { get; set; }

            /// <summary>
            /// Tokens generated by the model for reasoning.
            /// </summary>
            [JsonPropertyName("reasoning_tokens")]
            public int? ReasoningTokens { get; set; }
        }

        /// <summary>
        /// Класс, использующийся для подробного описания количества токенов в запросе к модели.
        /// </summary>
        public sealed class PromptTokensDetail
        {
            /// <summary>
            /// Audio input tokens present in the prompt.
            /// </summary>
            [JsonPropertyName("audio_tokens")]
            public int? AudioTokens { get; set; }

            /// <summary>
            /// Cached tokens present in the prompt.
            /// </summary>
            [JsonPropertyName("cached_tokens")]
            public int? CachedTokens { get; set; }
        }
    }
}
