using Content.Client.UserInterface.Controls;
using Content.Shared._WL.Emergency.Prototype;
using Content.Shared.AlertLevel;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Globalization;

namespace Content.Client._WL.Communications.UI;

[GenerateTypedNameReferences]
public sealed partial class NewCommunicationsConsoleMenu : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public bool CanAnnounce;
    public bool CanBroadcast;
    public bool CanCall;
    public bool AlertLevelSelectable;
    public bool EmergencySelectable;
    public bool CountdownStarted;
    public string CurrentLevel = string.Empty;
    public string CurrentEmergency = string.Empty;
    public TimeSpan? CountdownEnd;

    public event Action<string>? OnEmergencyLevel;
    public event Action? OnEmergencyShuttle;
    public event Action<string>? OnAlertLevel;
    public event Action<string>? OnAnnounce;
    public event Action<string>? OnBroadcast;

    public NewCommunicationsConsoleMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MessageInput.Placeholder = new Rope.Leaf(_loc.GetString("comms-console-menu-announcement-placeholder"));
        BroadcastInput.Placeholder = new Rope.Leaf(_loc.GetString("wl-console-menu-broadcast-placeholder"));

        var maxAnnounceLength = _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);
        MessageInput.OnTextChanged += (args) =>
        {
            if (args.Control.TextLength > maxAnnounceLength)
            {
                AnnounceButton.Disabled = true;
                AnnounceButton.ToolTip = Loc.GetString("comms-console-message-too-long");
            }
            else
            {
                AnnounceButton.Disabled = !CanAnnounce;
                AnnounceButton.ToolTip = null;

            }
        };

        AnnounceButton.OnPressed += _ => OnAnnounce?.Invoke(Rope.Collapse(MessageInput.TextRope));
        AnnounceButton.Disabled = !CanAnnounce;

        BroadcastButton.OnPressed += _ => OnBroadcast?.Invoke(Rope.Collapse(BroadcastInput.TextRope));
        BroadcastButton.Disabled = !CanBroadcast;

        AlertLevelButton.OnItemSelected += args =>
        {
            var metadata = AlertLevelButton.GetItemMetadata(args.Id);
            if (metadata != null && metadata is string cast)
            {
                OnAlertLevel?.Invoke(cast);
            }
        };

        EmergencyButton.OnItemSelected += args =>
        {
            var metadata = EmergencyButton.GetItemMetadata(args.Id);
            if (metadata != null && metadata is string cast)
            {
                OnEmergencyLevel?.Invoke(cast);
            }
        };

        EmergencyButton.Disabled = !EmergencySelectable;
        AlertLevelButton.Disabled = !AlertLevelSelectable;

        EmergencyShuttleButton.OnPressed += _ => OnEmergencyShuttle?.Invoke();
        EmergencyShuttleButton.Disabled = !CanCall;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCountdown();
    }

    // The current alert could make levels unselectable, so we need to ensure that the UI reacts properly.
    // If the current alert is unselectable, the only item in the alerts list will be
    // the current alert. Otherwise, it will be the list of alerts, with the current alert
    // selected.
    public void UpdateAlertLevels(List<string>? alerts, string currentAlert)
    {
        AlertLevelButton.Clear();

        if (alerts == null)
        {
            var name = currentAlert;

            if (!string.IsNullOrEmpty(currentAlert) && _prototypeManager.TryIndex<AlertLevelPrototype>(currentAlert, out var index))
            {
                if (_loc.TryGetString($"alert-level-{currentAlert.ToLower()}", out var locName))
                    name = locName;
                else if (!string.IsNullOrEmpty(index.SetName))
                    name = index.SetName;
            }

            AlertLevelButton.AddItem(name);
            AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, currentAlert);
        }
        else
        {
            foreach (var alert in alerts)
            {
                var name = alert;

                if (_prototypeManager.TryIndex<AlertLevelPrototype>(alert, out var index))
                {
                    if (_loc.TryGetString($"alert-level-{alert.ToLower()}", out var locName))
                    {
                        name = locName;
                    }
                    else if (!string.IsNullOrEmpty(index.SetName))
                        name = index.SetName;

                    AlertLevelButton.AddItem(name);
                    AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, alert);

                    if (alert == currentAlert)
                    {
                        AlertLevelButton.Modulate = index.Color;
                    }
                }

                if (alert == currentAlert)
                {
                    AlertLevelButton.Select(AlertLevelButton.ItemCount - 1);
                }
            }
        }
    }

    public void UpdateEmergency(List<string>? emergencys, string currentEmergency)
    {
        EmergencyButton.Clear();

        if (emergencys == null)
        {
            var name = currentEmergency;

            if (!_prototypeManager.TryIndex<EmergencyPrototype>(currentEmergency, out var index))
                return;
            if (_loc.TryGetString($"{index.Name}", out var locName))
            {
                name = locName;
            }
            else if (!string.IsNullOrEmpty(index.Name))
                name = index.Name;


            EmergencyButton.AddItem(name);
            EmergencyButton.SetItemMetadata(EmergencyButton.ItemCount - 1, currentEmergency);
        }
        else
        {
            foreach (var alert in emergencys)
            {
                var name = alert;

                if (_prototypeManager.TryIndex<EmergencyPrototype>(alert, out var index))
                {
                    if (_loc.TryGetString($"{index.Name}", out var locName))
                    {
                        name = locName;
                    }
                    else if (!string.IsNullOrEmpty(index.Name))
                        name = index.Name;

                    EmergencyButton.AddItem(name);
                    EmergencyButton.SetItemMetadata(EmergencyButton.ItemCount - 1, alert);
                }

                if (alert == currentEmergency)
                {
                    EmergencyButton.Select(EmergencyButton.ItemCount - 1);
                }
            }
        }
    }

    public void UpdateCountdown()
    {
        if (!CountdownStarted)
        {
            CountdownLabel.SetMessage(Loc.GetString("wl-console-menu-shuttle-no-call"));
            EmergencyShuttleButton.Text = Loc.GetString("comms-console-menu-call-shuttle");
            return;
        }

        var diff = MathHelper.Max((CountdownEnd - _timing.CurTime) ?? TimeSpan.Zero, TimeSpan.Zero);

        EmergencyShuttleButton.Text = Loc.GetString("comms-console-menu-recall-shuttle");
        var infoText = Loc.GetString($"wl-console-menu-time-remaining",
            ("time", diff.ToString(@"hh\:mm\:ss", CultureInfo.CurrentCulture)));
        CountdownLabel.SetMessage(infoText);
    }
}
