using System.Linq;
using System.Numerics;
using Content.Shared._WL.Records;
using Content.Shared._WL.Time;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._WL.Records;

[GenerateTypedNameReferences]
public sealed partial class RecordsTab : Control
{
    public Action<string>? OnMedicalRecordChanged;
    public Action<string>? OnSecurityRecordChanged;
    public Action<string>? OnEmploymentRecordChanged;
    public Action<string>? OnGeneralRecordNameChanged;
    public Action<string>? OnGeneralRecordAgeChanged;
    public Action<OptionButton.ItemSelectedEventArgs>? OnGeneralRecordConfederationChanged;
    public Action<string>? OnGeneralRecordCountryChanged;

    private readonly List<EducationEntryControls> _educationEntries = new();
    private readonly List<string> _residenceConfederationValues = new();
    private bool _updating;
    private int _characterAge;
    private string _species = string.Empty;
    private string _speciesDisplay = string.Empty;
    private string _sexDisplay = string.Empty;
    private string _confederationDisplay = string.Empty;
    private string _medicalStorage = string.Empty;
    private string _securityStorage = string.Empty;
    private string _employmentStorage = string.Empty;
    private int _height;
    private RecordsPreviewWindow? _previewWindow;

    public RecordsTab()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(MedicalTab, RecordTabContainer.PaddedTitle(Loc.GetString("records-medical")));
        TabContainer.SetTabTitle(SecurityTab, RecordTabContainer.PaddedTitle(Loc.GetString("records-security")));
        TabContainer.SetTabTitle(EmploymentTab, RecordTabContainer.PaddedTitle(Loc.GetString("records-employment")));

        PopulateEnumOptions(SecurityMaritalStatus, Enum.GetValues<RecordMaritalStatus>(), "records-marital");
        PopulateEnumOptions(EmploymentAcademicTitle, Enum.GetValues<RecordAcademicTitle>(), "records-academic-title-value");
        PopulateBooleanOptions(MedicalDnr);
        PopulateBooleanOptions(SecuritySupervision);
        ConfigureTextLimits();

        BindLineEdit(MedicalWeight, EmitMedical);
        BindLineEdit(MedicalPostmortem, EmitMedical);
        BindLineEdit(MedicalEmergencyContact, EmitMedical);
        BindLineEdit(MedicalRefusedTreatment, EmitMedical);
        MedicalLastUpdated.OnDateChanged += EmitMedical;
        BindTextEdit(MedicalSurgeries, EmitMedical);
        BindTextEdit(MedicalMedication, EmitMedical);
        BindTextEdit(MedicalPhysiological, EmitMedical);
        BindTextEdit(MedicalPsychological, EmitMedical);
        BindTextEdit(MedicalNotes, EmitMedical);
        MedicalDnr.OnItemSelected += args =>
        {
            MedicalDnr.SelectId(args.Id);
            EmitMedical();
        };

        BindLineEdit(SecurityResidenceCustom, EmitSecurity);
        BindLineEdit(SecurityResidencePlanet, EmitSecurity);
        BindLineEdit(SecurityResidenceStreet, EmitSecurity);
        BindLineEdit(SecurityResidenceUnit, EmitSecurity);
        BindLineEdit(SecurityResidenceDetails, EmitSecurity);
        BindLineEdit(SecurityFeatures, EmitSecurity);
        BindLineEdit(SecurityRelatives, EmitSecurity);
        BindLineEdit(SecurityEmergencyContact, EmitSecurity);
        SecurityLastUpdated.OnDateChanged += EmitSecurity;
        BindTextEdit(SecurityPermits, EmitSecurity);
        BindTextEdit(SecurityArrests, EmitSecurity);
        BindTextEdit(SecurityImprisonment, EmitSecurity);
        BindTextEdit(SecurityNotes, EmitSecurity);
        SecurityMaritalStatus.OnItemSelected += args =>
        {
            SecurityMaritalStatus.SelectId(args.Id);
            EmitSecurity();
        };
        SecuritySupervision.OnItemSelected += args =>
        {
            SecuritySupervision.SelectId(args.Id);
            EmitSecurity();
        };
        SecurityResidenceConfederation.OnItemSelected += args =>
        {
            SecurityResidenceConfederation.SelectId(args.Id);
            UpdateResidenceCustomVisibility();
            EmitSecurity();
        };

        EmploymentAcademicTitleDate.OnDateChanged += EmitEmployment;
        BindLineEdit(EmploymentAcademicTitleField, EmitEmployment);
        EmploymentLastUpdated.OnDateChanged += EmitEmployment;
        BindTextEdit(EmploymentLicenses, EmitEmployment);
        BindTextEdit(EmploymentHistory, EmitEmployment);
        BindTextEdit(EmploymentNotes, EmitEmployment);
        EmploymentAcademicTitle.OnItemSelected += args =>
        {
            EmploymentAcademicTitle.SelectId(args.Id);
            UpdateAcademicTitleVisibility(true);
            EmitEmployment();
        };
        UpdateAcademicTitleVisibility(false);
        AddEducation.OnPressed += _ => AddEducationEntry(new EducationRecordData(), true);

        NameEdit.OnTextChanged += _ =>
        {
            if (!_updating)
                OnGeneralRecordNameChanged?.Invoke(NameEdit.Text.Trim());
            UpdatePreview();
        };
        BindDatePart(BirthDayEdit, 2, UpdateBirthDate);
        BindDatePart(BirthMonthEdit, 2, UpdateBirthDate);
        CountryEdit.OnTextChanged += _ =>
        {
            if (!_updating)
                OnGeneralRecordCountryChanged?.Invoke(CountryEdit.Text.Trim());
            UpdatePreview();
        };
        ConfederationButton.OnItemSelected += args =>
        {
            OnGeneralRecordConfederationChanged?.Invoke(args);
            UpdatePreview();
        };
        RecordTabs.OnTabChanged += _ => UpdatePreview();
        PreviewButton.OnPressed += _ => OpenPreview();
        OnResized += UpdateEducationLayout;
    }

    public void SetResidenceRegions(IEnumerable<(string DisplayName, Texture? Icon)> regions, Texture? otherIcon)
    {
        _residenceConfederationValues.Clear();
        SecurityResidenceConfederation.Clear();

        foreach (var (displayName, icon) in regions.DistinctBy(region => region.DisplayName))
        {
            _residenceConfederationValues.Add(displayName);
            var id = _residenceConfederationValues.Count - 1;
            if (icon == null)
                SecurityResidenceConfederation.AddItem(displayName, id);
            else
                SecurityResidenceConfederation.AddItem(icon, displayName, id);
        }

        _residenceConfederationValues.Add(string.Empty);
        var otherId = _residenceConfederationValues.Count - 1;
        var other = Loc.GetString("records-residence-confederation-other");
        if (otherIcon == null)
            SecurityResidenceConfederation.AddItem(other, otherId);
        else
            SecurityResidenceConfederation.AddItem(otherIcon, other, otherId);

        SecurityResidenceConfederation.SelectId(otherId);
        UpdateResidenceCustomVisibility();
    }

    public void SetRecords(
        string medicalStorage,
        string securityStorage,
        string employmentStorage,
        string species,
        string speciesDisplay,
        string sexDisplay,
        string confederationDisplay,
        string fullName,
        string country,
        string storedDateOfBirth,
        int age,
        int height)
    {
        _updating = true;
        _characterAge = age;
        _species = species;
        _speciesDisplay = speciesDisplay;
        _sexDisplay = sexDisplay;
        _confederationDisplay = confederationDisplay;
        _height = height;
        _medicalStorage = medicalStorage;
        _securityStorage = securityStorage;
        _employmentStorage = employmentStorage;
        NameEdit.Text = fullName;
        CountryEdit.Text = country;
        SetMedical(StructuredCharacterRecords.ReadMedical(medicalStorage));
        SetSecurity(StructuredCharacterRecords.ReadSecurity(securityStorage));
        SetEmployment(StructuredCharacterRecords.ReadEmployment(employmentStorage));
        var normalizedDateOfBirth = SetDateOfBirth(storedDateOfBirth);
        var organic = RecordSpeciesClassification.IsOrganic(species);
        var manufactured = RecordSpeciesClassification.IsManufactured(species);
        MedicalProcedureFields.Visible = organic || manufactured;
        MedicalProceduresLabel.Text = Loc.GetString(manufactured
            ? "records-repair-records"
            : "records-surgeries");
        OrganicMedicalFields.Visible = organic;
        BirthDateLabel.Text = Loc.GetString(manufactured
            ? "records-date-of-manufacture-edit"
            : "records-date-of-birth-edit");
        _updating = false;
        UpdatePreview();
        UpdateEducationLayout();

        if (normalizedDateOfBirth != null && normalizedDateOfBirth != storedDateOfBirth)
            OnGeneralRecordAgeChanged?.Invoke(normalizedDateOfBirth);
    }

    private string? SetDateOfBirth(string storedDate)
    {
        if (WLCalendar.TryParseBirthDate(storedDate, out var birthDate))
        {
            birthDate = WLCalendar.RecalculateBirthDate(_characterAge, birthDate);
            BirthDayEdit.Text = birthDate.Day.ToString("00");
            BirthMonthEdit.Text = birthDate.Month.ToString("00");
            BirthYearEdit.Text = birthDate.Year.ToString("0000");
            BirthDateValidationLabel.Visible = false;
            return WLCalendar.FormatBirthDate(birthDate);
        }

        BirthDayEdit.Text = string.Empty;
        BirthMonthEdit.Text = string.Empty;
        BirthYearEdit.Text = string.Empty;
        BirthDateValidationLabel.Visible = !string.IsNullOrWhiteSpace(storedDate);
        BirthDateValidationLabel.Text = Loc.GetString("records-date-of-birth-legacy-invalid", ("date", storedDate));
        return null;
    }

    private void UpdateBirthDate()
    {
        if (_updating)
            return;

        var dayText = BirthDayEdit.Text.Trim();
        var monthText = BirthMonthEdit.Text.Trim();
        if (dayText.Length == 0 && monthText.Length == 0)
        {
            BirthYearEdit.Text = string.Empty;
            BirthDateValidationLabel.Visible = false;
            OnGeneralRecordAgeChanged?.Invoke(string.Empty);
            UpdatePreview();
            return;
        }

        if (!int.TryParse(dayText, out var day) ||
            !int.TryParse(monthText, out var month) ||
            !WLCalendar.TryCreateBirthDate(_characterAge, day, month, out var birthDate))
        {
            BirthYearEdit.Text = string.Empty;
            BirthDateValidationLabel.Text = Loc.GetString("records-date-of-birth-invalid");
            BirthDateValidationLabel.Visible = dayText.Length > 0 && monthText.Length > 0;
            UpdatePreview();
            return;
        }

        BirthYearEdit.Text = birthDate.Year.ToString("0000");
        BirthDateValidationLabel.Visible = false;
        OnGeneralRecordAgeChanged?.Invoke(WLCalendar.FormatBirthDate(birthDate));
        UpdatePreview();
    }

    private void SetMedical(MedicalRecordData record)
    {
        MedicalWeight.Text = record.Weight;
        MedicalPostmortem.Text = record.PostmortemInstructions;
        MedicalDnr.SelectId(record.DoNotResuscitate ? 1 : 0);
        MedicalRefusedTreatment.Text = record.RefusedTreatment;
        MedicalEmergencyContact.Text = record.EmergencyContact;
        SetText(MedicalSurgeries, record.Surgeries);
        SetText(MedicalMedication, record.Medication);
        SetText(MedicalPhysiological, record.PhysiologicalNotes);
        SetText(MedicalPsychological, record.PsychologicalNotes);
        SetText(MedicalNotes, record.Notes);
        MedicalLastUpdated.SetText(record.LastUpdated);
    }

    private void SetSecurity(SecurityRecordData record)
    {
        var residence = StructuredCharacterRecords.ReadResidence(record.Residence);
        var confederationIndex = _residenceConfederationValues.FindIndex(value =>
            !string.IsNullOrEmpty(value) && value == residence.Confederation);
        if (confederationIndex < 0)
        {
            confederationIndex = _residenceConfederationValues.FindIndex(string.IsNullOrEmpty);
            SecurityResidenceCustom.Text = residence.Confederation;
        }
        else
        {
            SecurityResidenceCustom.Text = string.Empty;
        }

        SecurityResidenceConfederation.SelectId(confederationIndex);
        SecurityResidencePlanet.Text = residence.Planet;
        SecurityResidenceStreet.Text = residence.Street;
        SecurityResidenceUnit.Text = residence.Unit;
        SecurityResidenceDetails.Text = residence.Details;
        UpdateResidenceCustomVisibility();
        SecurityFeatures.Text = record.IdentifyingFeatures;
        SecurityMaritalStatus.SelectId((int) record.MaritalStatus);
        SecurityRelatives.Text = record.CloseRelatives;
        SecurityEmergencyContact.Text = record.EmergencyContact;
        SetText(SecurityPermits, record.Permits);
        SecuritySupervision.SelectId(record.UnderSecuritySupervision ? 1 : 0);
        SetText(SecurityArrests, record.ArrestHistory);
        SetText(SecurityImprisonment, record.ImprisonmentHistory);
        SetText(SecurityNotes, record.Notes);
        SecurityLastUpdated.SetText(record.LastUpdated);
    }

    private void SetEmployment(EmploymentRecordData record)
    {
        foreach (var entry in _educationEntries)
            entry.Container.Orphan();
        _educationEntries.Clear();

        foreach (var education in record.Education)
            AddEducationEntry(education, false);

        EmploymentAcademicTitle.SelectId((int) record.AcademicTitle);
        EmploymentAcademicTitleField.Text = record.AcademicTitleField;
        EmploymentAcademicTitleDate.SetText(record.AcademicTitleDate);
        UpdateAcademicTitleVisibility(false);
        SetText(EmploymentLicenses, record.Licenses);
        SetText(EmploymentHistory, record.EmploymentHistory);
        SetText(EmploymentNotes, record.Notes);
        EmploymentLastUpdated.SetText(record.LastUpdated);
        UpdateEducationButton();
    }

    private void EmitMedical()
    {
        if (_updating)
            return;

        _medicalStorage = StructuredCharacterRecords.WriteMedical(new MedicalRecordData
        {
            Weight = MedicalWeight.Text,
            PostmortemInstructions = MedicalPostmortem.Text,
            DoNotResuscitate = MedicalDnr.SelectedId == 1,
            RefusedTreatment = MedicalRefusedTreatment.Text,
            EmergencyContact = MedicalEmergencyContact.Text,
            Surgeries = GetText(MedicalSurgeries),
            Medication = GetText(MedicalMedication),
            PhysiologicalNotes = GetText(MedicalPhysiological),
            PsychologicalNotes = GetText(MedicalPsychological),
            Notes = GetText(MedicalNotes),
            LastUpdated = MedicalLastUpdated.Text,
        });
        OnMedicalRecordChanged?.Invoke(_medicalStorage);
        UpdatePreview();
    }

    private void EmitSecurity()
    {
        if (_updating)
            return;

        _securityStorage = StructuredCharacterRecords.WriteSecurity(new SecurityRecordData
        {
            Residence = StructuredCharacterRecords.WriteResidence(new ResidenceRecordData
            {
                Confederation = GetSelectedResidenceConfederation(),
                Planet = SecurityResidencePlanet.Text,
                Street = SecurityResidenceStreet.Text,
                Unit = SecurityResidenceUnit.Text,
                Details = SecurityResidenceDetails.Text,
            }),
            IdentifyingFeatures = SecurityFeatures.Text,
            MaritalStatus = (RecordMaritalStatus) SecurityMaritalStatus.SelectedId,
            CloseRelatives = SecurityRelatives.Text,
            EmergencyContact = SecurityEmergencyContact.Text,
            Permits = GetText(SecurityPermits),
            UnderSecuritySupervision = SecuritySupervision.SelectedId == 1,
            ArrestHistory = GetText(SecurityArrests),
            ImprisonmentHistory = GetText(SecurityImprisonment),
            Notes = GetText(SecurityNotes),
            LastUpdated = SecurityLastUpdated.Text,
        });
        OnSecurityRecordChanged?.Invoke(_securityStorage);
        UpdatePreview();
    }

    private void UpdateResidenceCustomVisibility()
    {
        ResidenceCustomRow.Visible = IsCustomResidenceSelected();
    }

    private bool IsCustomResidenceSelected()
    {
        return TryGetSelectedResidenceConfederation(out var confederation) &&
               string.IsNullOrEmpty(confederation);
    }

    private string GetSelectedResidenceConfederation()
    {
        if (!TryGetSelectedResidenceConfederation(out var confederation))
            return string.Empty;

        return string.IsNullOrEmpty(confederation)
            ? SecurityResidenceCustom.Text
            : confederation;
    }

    private bool TryGetSelectedResidenceConfederation(out string confederation)
    {
        var selected = SecurityResidenceConfederation.SelectedId;
        if (selected < 0 || selected >= _residenceConfederationValues.Count)
        {
            confederation = string.Empty;
            return false;
        }

        confederation = _residenceConfederationValues[selected];
        return true;
    }

    private void EmitEmployment()
    {
        if (_updating)
            return;

        var hasAcademicTitle = EmploymentAcademicTitle.SelectedId != (int) RecordAcademicTitle.NotApplicable;
        var record = new EmploymentRecordData
        {
            AcademicTitle = (RecordAcademicTitle) EmploymentAcademicTitle.SelectedId,
            AcademicTitleField = hasAcademicTitle ? EmploymentAcademicTitleField.Text : string.Empty,
            AcademicTitleDate = hasAcademicTitle ? EmploymentAcademicTitleDate.Text : string.Empty,
            Licenses = GetText(EmploymentLicenses),
            EmploymentHistory = GetText(EmploymentHistory),
            Notes = GetText(EmploymentNotes),
            LastUpdated = EmploymentLastUpdated.Text,
        };

        foreach (var entry in _educationEntries)
        {
            record.Education.Add(new EducationRecordData
            {
                Specialty = entry.Specialty.Text,
                SpecialtyGroup = entry.SpecialtyGroupValues[entry.SpecialtyGroup.SelectedId],
                SpecialtySubgroup = entry.SpecialtySubgroupValues[entry.SpecialtySubgroup.SelectedId],
                Degree = (RecordAcademicDegree) entry.Degree.SelectedId,
                Institution = entry.Institution.Text,
                DiplomaDate = entry.DiplomaDate.Text,
            });
        }

        _employmentStorage = StructuredCharacterRecords.WriteEmployment(record);
        OnEmploymentRecordChanged?.Invoke(_employmentStorage);
        UpdatePreview();
    }

    private void ConfigureTextLimits()
    {
        MedicalSurgeries.SetCharacterLimit(StructuredCharacterRecords.MaxLongTextLength);
        MedicalMedication.SetCharacterLimit(StructuredCharacterRecords.MaxLongTextLength);
        MedicalPhysiological.SetCharacterLimit(StructuredCharacterRecords.MaxLongTextLength);
        MedicalPsychological.SetCharacterLimit(StructuredCharacterRecords.MaxLongTextLength);
        MedicalNotes.SetCharacterLimit(StructuredCharacterRecords.MaxNotesTextLength);

        SecurityPermits.SetCharacterLimit(StructuredCharacterRecords.MaxLongTextLength);
        SecurityArrests.SetCharacterLimit(StructuredCharacterRecords.MaxLongTextLength);
        SecurityImprisonment.SetCharacterLimit(StructuredCharacterRecords.MaxLongTextLength);
        SecurityNotes.SetCharacterLimit(StructuredCharacterRecords.MaxNotesTextLength);

        EmploymentLicenses.SetCharacterLimit(StructuredCharacterRecords.MaxLongTextLength);
        EmploymentHistory.SetCharacterLimit(StructuredCharacterRecords.MaxEmploymentHistoryLength);
        EmploymentNotes.SetCharacterLimit(StructuredCharacterRecords.MaxNotesTextLength);
    }

    private void UpdateAcademicTitleVisibility(bool clearHiddenValues)
    {
        var visible = EmploymentAcademicTitle.SelectedId != (int) RecordAcademicTitle.NotApplicable;
        AcademicTitleFieldContainer.Visible = visible;
        AcademicTitleDateContainer.Visible = visible;

        if (visible || !clearHiddenValues)
            return;

        var wasUpdating = _updating;
        _updating = true;
        EmploymentAcademicTitleField.Text = string.Empty;
        EmploymentAcademicTitleDate.SetText(string.Empty);
        _updating = wasUpdating;
    }

    private void AddEducationEntry(EducationRecordData record, bool emit)
    {
        if (_educationEntries.Count >= StructuredCharacterRecords.MaxEducationEntries)
            return;

        var specialty = new LineEdit { Text = record.Specialty, HorizontalExpand = true, MinWidth = 230 };
        var specialtyGroup = new RecordOptionButton { HorizontalExpand = true, MinWidth = 230, MaxWidth = 600 };
        var specialtyGroupValues = new List<string> { string.Empty };
        specialtyGroup.AddItem(Loc.GetString("records-value-not-specified"), 0);
        foreach (var group in StructuredCharacterRecords.SpecialtyGroups)
        {
            specialtyGroupValues.Add(group);
            specialtyGroup.AddItem(Loc.GetString($"records-specialty-group-value-{group}"), specialtyGroupValues.Count - 1);
        }
        var specialtyGroupIndex = specialtyGroupValues.IndexOf(record.SpecialtyGroup);
        if (specialtyGroupIndex < 0 && !string.IsNullOrWhiteSpace(record.SpecialtyGroup))
        {
            specialtyGroupValues.Add(record.SpecialtyGroup);
            specialtyGroupIndex = specialtyGroupValues.Count - 1;
            specialtyGroup.AddItem(record.SpecialtyGroup, specialtyGroupIndex);
        }
        specialtyGroup.SelectId(Math.Max(0, specialtyGroupIndex));
        var specialtySubgroup = new RecordOptionButton { HorizontalExpand = true, MinWidth = 230, MaxWidth = 600 };
        var specialtySubgroupValues = new List<string>();
        void PopulateSpecialtySubgroups(string selected)
        {
            specialtySubgroup.Clear();
            specialtySubgroupValues.Clear();
            specialtySubgroupValues.Add(string.Empty);
            specialtySubgroup.AddItem(Loc.GetString("records-value-not-specified"), 0);

            var selectedGroup = specialtyGroupValues[specialtyGroup.SelectedId];
            foreach (var subgroup in SpecialtyGroupCatalog.GetSubgroups(selectedGroup))
            {
                specialtySubgroupValues.Add(subgroup);
                specialtySubgroup.AddItem(
                    Loc.GetString(SpecialtyGroupCatalog.GetSubgroupLocalizationKey(subgroup)),
                    specialtySubgroupValues.Count - 1);
            }

            var subgroupIndex = specialtySubgroupValues.IndexOf(selected);
            if (subgroupIndex < 0 && !string.IsNullOrWhiteSpace(selected))
            {
                specialtySubgroupValues.Add(selected);
                subgroupIndex = specialtySubgroupValues.Count - 1;
                var displayName = SpecialtyGroupCatalog.ContainsSubgroup(selected)
                    ? Loc.GetString(SpecialtyGroupCatalog.GetSubgroupLocalizationKey(selected))
                    : selected;
                specialtySubgroup.AddItem(displayName, subgroupIndex);
            }

            specialtySubgroup.SelectId(Math.Max(0, subgroupIndex));
        }
        PopulateSpecialtySubgroups(record.SpecialtySubgroup);
        var degree = new RecordOptionButton { HorizontalExpand = true, MinWidth = 230, MaxWidth = 380 };
        PopulateEnumOptions(degree, Enum.GetValues<RecordAcademicDegree>(), "records-degree");
        degree.SelectId((int) record.Degree);
        var institution = new LineEdit { Text = record.Institution, HorizontalExpand = true, MinWidth = 230 };
        var diplomaDate = new RecordDateEdit { HorizontalExpand = true, MinWidth = 230 };
        diplomaDate.SetText(record.DiplomaDate);

        var specialtyField = CreateEducationField("records-specialty", specialty, out var specialtyLabel);
        var specialtyGroupField = CreateEducationField("records-specialty-group", specialtyGroup, out var specialtyGroupLabel);
        var specialtySubgroupField = CreateEducationField("records-specialty-subgroup", specialtySubgroup, out var specialtySubgroupLabel);
        var degreeField = CreateEducationField("records-degree", degree, out var degreeLabel);
        var diplomaDateField = CreateEducationField("records-diploma-date", diplomaDate, out var diplomaDateLabel);
        var institutionField = CreateEducationField("records-institution", institution, out var institutionLabel);

        var firstRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 10,
            Children =
            {
                specialtyField,
                specialtyGroupField,
            },
        };
        var secondRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 10,
            Children =
            {
                specialtySubgroupField,
                degreeField,
            },
        };
        var thirdRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 10,
            Children =
            {
                institutionField,
                diplomaDateField,
            },
        };

        var remove = new Button
        {
            Text = Loc.GetString("records-remove-education"),
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(0, 4, 0, 0),
        };
        var title = new Label
        {
            StyleClasses = { "LabelBig" },
            FontColorOverride = Color.FromHex("#C7C7CC"),
        };
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10),
            SeparationOverride = 6,
            Children = { title, firstRow, secondRow, thirdRow, remove },
        };
        var container = new PanelContainer
        {
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Stretch,
            MaxWidth = 1260,
            Margin = new Thickness(0, 4),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#18181C"),
                BorderColor = Color.FromHex("#46464E"),
                BorderThickness = new Thickness(1),
            },
            Children = { content },
        };
        var controls = new EducationEntryControls(
            container,
            title,
            firstRow,
            secondRow,
            thirdRow,
            [
                new EducationFieldLabel(specialtyLabel, "records-specialty"),
                new EducationFieldLabel(specialtyGroupLabel, "records-specialty-group"),
                new EducationFieldLabel(specialtySubgroupLabel, "records-specialty-subgroup"),
                new EducationFieldLabel(degreeLabel, "records-degree"),
                new EducationFieldLabel(institutionLabel, "records-institution"),
                new EducationFieldLabel(diplomaDateLabel, "records-diploma-date"),
            ],
            specialty,
            specialtyGroup,
            specialtyGroupValues,
            specialtySubgroup,
            specialtySubgroupValues,
            degree,
            institution,
            diplomaDate);
        _educationEntries.Add(controls);
        EducationEntries.AddChild(container);

        BindLineEdit(specialty, EmitEmployment);
        BindLineEdit(institution, EmitEmployment);
        diplomaDate.OnDateChanged += EmitEmployment;
        degree.OnItemSelected += args =>
        {
            degree.SelectId(args.Id);
            EmitEmployment();
        };
        specialtyGroup.OnItemSelected += args =>
        {
            specialtyGroup.SelectId(args.Id);
            PopulateSpecialtySubgroups(string.Empty);
            EmitEmployment();
        };
        specialtySubgroup.OnItemSelected += args =>
        {
            specialtySubgroup.SelectId(args.Id);
            EmitEmployment();
        };
        remove.OnPressed += _ =>
        {
            controls.Container.Orphan();
            _educationEntries.Remove(controls);
            RenumberEducationEntries();
            UpdateEducationButton();
            EmitEmployment();
        };

        RenumberEducationEntries();
        UpdateEducationLayout();
        UpdateEducationButton();
        if (emit)
            EmitEmployment();
    }

    private BoxContainer CreateEducationField(string labelKey, Control input, out Label label)
    {
        label = new Label
        {
            Text = Loc.GetString(labelKey),
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(0, 0, 0, 2),
        };
        return new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            MinWidth = 250,
            Children =
            {
                label,
                input,
            },
        };
    }

    private void UpdateEducationButton()
    {
        AddEducation.Disabled = _educationEntries.Count >= StructuredCharacterRecords.MaxEducationEntries;
    }

    private void RenumberEducationEntries()
    {
        for (var i = 0; i < _educationEntries.Count; i++)
        {
            _educationEntries[i].Title.Text = Loc.GetString("records-education-number", ("number", i + 1));
            foreach (var field in _educationEntries[i].FieldLabels)
            {
                field.Label.Text = Loc.GetString(field.LocalizationKey) + (i == 0 ? string.Empty : $" ({i + 1})");
            }
        }
    }

    private void UpdateEducationLayout()
    {
        var rowOrientation = FormColumn.Width >= 760
            ? BoxContainer.LayoutOrientation.Horizontal
            : BoxContainer.LayoutOrientation.Vertical;

        ResidenceFirstRow.Orientation = rowOrientation;
        ResidenceSecondRow.Orientation = rowOrientation;
        AcademicTitleFirstRow.Orientation = rowOrientation;

        foreach (var entry in _educationEntries)
        {
            entry.FirstRow.Orientation = rowOrientation;
            entry.SecondRow.Orientation = rowOrientation;
            entry.ThirdRow.Orientation = rowOrientation;
        }
    }

    private void OpenPreview()
    {
        if (_previewWindow?.IsOpen == true)
        {
            _previewWindow.MoveToFront();
            return;
        }

        _previewWindow = new RecordsPreviewWindow();
        _previewWindow.OnClose += () => _previewWindow = null;
        UpdatePreview();
        _previewWindow.FitToScreen(Root?.Size ?? new Vector2(900, 650));
        _previewWindow.OpenCentered();
    }

    private void UpdatePreview()
    {
        if (_previewWindow == null)
            return;

        var noData = Loc.GetString("records-value-no-data");
        var date = GetCurrentBirthDate();
        var identity = new RecordIdentityData(
            ValueOr(NameEdit.Text, noData),
            string.Empty,
            string.Empty,
            string.Empty,
            ValueOr(NameEdit.Text, noData),
            Loc.GetString(RecordSpeciesClassification.IsManufactured(_species)
                ? "records-date-of-manufacture-edit"
                : "records-date-of-birth-edit"),
            ValueOr(date, noData),
            ValueOr(_sexDisplay, noData),
            ValueOr(_speciesDisplay, noData),
            $"{_height} {Loc.GetString("records-height-unit-centimeters")}",
            noData,
            ValueOr(_confederationDisplay, noData),
            ValueOr(CountryEdit.Text, noData));

        _previewWindow.SetRecords(
            RecordViewBuilder.Medical(identity, _medicalStorage, _species, Loc.GetString),
            RecordViewBuilder.Security(identity, _securityStorage, Loc.GetString),
            RecordViewBuilder.Employment(identity, _employmentStorage, Loc.GetString),
            RecordTabs.CurrentTab);
    }

    private string GetCurrentBirthDate()
    {
        var day = BirthDayEdit.Text.Trim();
        var month = BirthMonthEdit.Text.Trim();
        var year = BirthYearEdit.Text.Trim();
        return day.Length == 0 || month.Length == 0 || year.Length == 0
            ? string.Empty
            : $"{day}.{month}.{year}";
    }

    private static string ValueOr(string value, string fallback) =>
        string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();

    private void PopulateBooleanOptions(RecordOptionButton button)
    {
        button.AddItem(Loc.GetString("records-value-no"), 0);
        button.AddItem(Loc.GetString("records-value-yes"), 1);
        button.SelectId(0);
    }

    private void BindDatePart(LineEdit edit, int maxLength, Action callback)
    {
        edit.OnTextChanged += _ =>
        {
            if (_updating)
                return;

            var sanitized = new string(edit.Text
                .Where(character => character is >= '0' and <= '9')
                .Take(maxLength)
                .ToArray());
            if (edit.Text != sanitized)
            {
                _updating = true;
                edit.Text = sanitized;
                edit.CursorPosition = Math.Min(edit.CursorPosition, sanitized.Length);
                _updating = false;
            }

            callback();
        };
    }

    private static void BindLineEdit(LineEdit edit, Action callback)
    {
        edit.OnTextChanged += _ => callback();
    }

    private static void BindTextEdit(RecordTextEdit edit, Action callback)
    {
        edit.OnTextChanged += _ => callback();
    }

    private void PopulateEnumOptions<T>(RecordOptionButton button, IEnumerable<T> values, string keyPrefix) where T : struct, Enum
    {
        foreach (var value in values)
            button.AddItem(
                Loc.GetString($"{keyPrefix}-{value.ToString().ToLowerInvariant()}"),
                value.GetHashCode());
        button.SelectId(0);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _previewWindow?.Close();
        _previewWindow = null;
    }

    private static string GetText(RecordTextEdit edit) => Rope.Collapse(edit.TextRope).Trim();
    private static void SetText(RecordTextEdit edit, string value) => edit.TextRope = new Rope.Leaf(value);

    private sealed record EducationEntryControls(
        PanelContainer Container,
        Label Title,
        BoxContainer FirstRow,
        BoxContainer SecondRow,
        BoxContainer ThirdRow,
        IReadOnlyList<EducationFieldLabel> FieldLabels,
        LineEdit Specialty,
        OptionButton SpecialtyGroup,
        IReadOnlyList<string> SpecialtyGroupValues,
        OptionButton SpecialtySubgroup,
        IReadOnlyList<string> SpecialtySubgroupValues,
        OptionButton Degree,
        LineEdit Institution,
        RecordDateEdit DiplomaDate);

    private sealed record EducationFieldLabel(Label Label, string LocalizationKey);
}
