using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.Records;

[GenerateTypedNameReferences]
public sealed partial class RecordsPreviewWindow : FancyWindow
{
    public RecordsPreviewWindow()
    {
        RobustXamlLoader.Load(this);
        TabContainer.SetTabTitle(MedicalView, RecordTabContainer.PaddedTitle(Loc.GetString("records-medical")));
        TabContainer.SetTabTitle(SecurityView, RecordTabContainer.PaddedTitle(Loc.GetString("records-security")));
        TabContainer.SetTabTitle(EmploymentView, RecordTabContainer.PaddedTitle(Loc.GetString("records-employment")));
        DismissButton.OnPressed += _ => Close();
    }

    public void SetRecords(RecordViewData medical, RecordViewData security, RecordViewData employment, int currentTab)
    {
        MedicalView.SetData(medical);
        SecurityView.SetData(security);
        EmploymentView.SetData(employment);
        PreviewTabs.CurrentTab = currentTab;
    }

    public void FitToScreen(Vector2 available)
    {
        var width = Math.Clamp(available.X - 48, 640, 900);
        var height = Math.Clamp(available.Y - 48, 460, 650);
        MinSize = new Vector2(Math.Min(720, width), Math.Min(500, height));
        SetSize = new Vector2(width, height);
    }
}
